import type { Commit } from "./types";
import { FILES } from "./files";

export const COMMITS: Commit[] = [
  {
    hash: "e7c1a04b92d85f13c6e0aa47b1d29f80",
    short: "e7c1a04",
    author: { name: "Hovhannes Mkhitaryan", handle: "hovinthenorth" },
    date: "2026-09-10T05:18:00Z",
    message: "Reload the map on SIGHUP",
    body: "Adding a channel is a file change, not a restart. In-flight collect windows keep the map they started with.",
    files: [
      {
        path: "agent/python/relay.py",
        status: "modified",
        additions: 28,
        deletions: 8,
        patch: [
          "@@ agent/python/relay.py",
          "+class Runtime:",
          "+    def reload(self) -> None:",
          "+        self.mapping = load_mapping_from(self.source)",
          "+        self.guard = ScopeGuard(self.mapping)",
          "+if hasattr(signal, \"SIGHUP\"):",
          "+    signal.signal(signal.SIGHUP, lambda *_: runtime.reload())",
        ].join("\n"),
      },
      {
        path: "agent/node/relay.ts",
        status: "modified",
        additions: 22,
        deletions: 6,
        patch: [
          "@@ agent/node/relay.ts",
          "+if (process.platform !== \"win32\") {",
          "+  process.on(\"SIGHUP\", () => { void runtime.reload(); });",
          "+}",
        ].join("\n"),
      },
      {
        path: "docs/scoped-relays.md",
        status: "modified",
        additions: 6,
        deletions: 0,
        patch: [
          "@@ docs/scoped-relays.md",
          "+## Reload",
          "+`SIGHUP` rebuilds the mapping and the wall.",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "b3d90e18c44a7f02e91c6b5d0a8e3174",
    short: "b3d90e1",
    author: { name: "Grok", handle: "grok" },
    date: "2026-09-10T05:02:00Z",
    message: "Redact ids outside the wall",
    body: "Unknown channel ids never appear in logs, exceptions, or reports. Substitute <outside-scope>.",
    files: [
      {
        path: "agent/python/scope.py",
        status: "modified",
        additions: 14,
        deletions: 2,
        patch: [
          "@@ agent/python/scope.py",
          "+    def redact(self, channel_id: str) -> str:",
          "+        return channel_id if self.allow(channel_id) else \"<outside-scope>\"",
          "+    def drop(self, channel_id: str, reason: str) -> None:",
          "+        logging.info(\"dropped event source=<outside-scope> reason=%s\", reason)",
        ].join("\n"),
      },
      {
        path: "agent/node/scope.ts",
        status: "modified",
        additions: 10,
        deletions: 1,
        patch: [
          "@@ agent/node/scope.ts",
          "+  redact(channelId: string): string {",
          "+    return this.allow(channelId) ? channelId : \"<outside-scope>\";",
          "+  }",
        ].join("\n"),
      },
      {
        path: "agent/python/report.py",
        status: "added",
        additions: 24,
        deletions: 0,
        patch: [
          "@@ agent/python/report.py",
          "+def format_report(*, mapping, guard, broadcast_id, reply_count, collect_seconds) -> str:",
          "+    guard.require(broadcast_id, \"report\")",
          "+    return f\"broadcast: {guard.redact(broadcast_id)}\"",
        ].join("\n"),
      },
      {
        path: "agent/node/report.ts",
        status: "added",
        additions: 22,
        deletions: 0,
        patch: [
          "@@ agent/node/report.ts",
          "+export function formatReport(opts) {",
          "+  opts.guard.require(opts.broadcastId, \"report\");",
          "+  return `broadcast: ${opts.guard.redact(opts.broadcastId)}`;",
        ].join("\n"),
      },
      {
        path: "agent/python/test_scope.py",
        status: "modified",
        additions: 8,
        deletions: 1,
        patch: [
          "@@ agent/python/test_scope.py",
          "+def test_redact_does_not_echo_unknown_id():",
          "+    assert guard.redact(\"C0SECRET\") == \"<outside-scope>\"",
          "+    assert \"C0SECRET\" not in str(err)",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "6f12c9aae03b47d1c8e90f25a4b176c2",
    short: "6f12c9a",
    author: { name: "Grok", handle: "grok" },
    date: "2026-09-10T04:36:00Z",
    message: "Accept mapping URLs",
    body: "--mapping is a path or https://. The agent fetches that one document. Nothing else.",
    files: [
      {
        path: "agent/python/mapping.py",
        status: "modified",
        additions: 16,
        deletions: 2,
        patch: [
          "@@ agent/python/mapping.py",
          "+def read_source(source: str) -> str:",
          "+    if source.startswith((\"http://\", \"https://\")):",
          "+        req = Request(source, headers={\"User-Agent\": \"axiom-relay/0.2\"})",
          "+        with urlopen(req, timeout=15) as resp:",
          "+            return resp.read().decode(\"utf-8\")",
          "+    return Path(source).read_text(encoding=\"utf-8\")",
        ].join("\n"),
      },
      {
        path: "agent/node/mapping.ts",
        status: "modified",
        additions: 12,
        deletions: 2,
        patch: [
          "@@ agent/node/mapping.ts",
          "+export async function readSource(source: string): Promise<string> {",
          "+  if (source.startsWith(\"http://\") || source.startsWith(\"https://\")) {",
          "+    const res = await fetch(source, { headers: { \"User-Agent\": \"axiom-relay/0.2\" } });",
          "+    return await res.text();",
          "+  }",
          "+  return readFileSync(source, \"utf8\");",
        ].join("\n"),
      },
      {
        path: "docs/setup.md",
        status: "modified",
        additions: 10,
        deletions: 3,
        patch: [
          "@@ docs/setup.md",
          "+`--mapping` is a path or an `https://` URL:",
          "+python agent/python/relay.py --mapping https://example.com/team.growth.md --dry-run",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "2a8e4c71d90b35f16e0aa92c47d1b803",
    short: "2a8e4c7",
    author: { name: "Hovhannes Mkhitaryan", handle: "hovinthenorth" },
    date: "2026-09-10T04:12:00Z",
    message: "Freeze PROTOCOL.md at v0.2",
    body: "The contract is the product. Implementations may add platforms. They may not add curiosity.",
    files: [
      {
        path: "PROTOCOL.md",
        status: "added",
        additions: 62,
        deletions: 0,
        patch: [
          "@@ PROTOCOL.md",
          "+# PROTOCOL",
          "+Frozen at v0.2. Implementations may add platforms. They may not add curiosity.",
          "+## 3. The wall",
          "+Unknown ids are dropped before the adapter sees the event.",
          "+## 5. Reload",
          "+`SIGHUP` re-reads the mapping source and rebuilds the wall.",
        ].join("\n"),
      },
      {
        path: "schema/channels.md",
        status: "modified",
        additions: 6,
        deletions: 1,
        patch: [
          "@@ schema/channels.md",
          "+Contract: PROTOCOL.md (frozen v0.2).",
          "+6. Unknown ids never appear in logs, exceptions, or reports.",
        ].join("\n"),
      },
      {
        path: "examples/discord.md",
        status: "added",
        additions: 18,
        deletions: 0,
        patch: [
          "@@ examples/discord.md",
          "+platform: discord",
          "+scope: team.growth",
          "+Same topology as mapping.md. Different snowflakes. Same wall.",
        ].join("\n"),
      },
      {
        path: "CONTRIBUTING.md",
        status: "modified",
        additions: 4,
        deletions: 1,
        patch: [
          "@@ CONTRIBUTING.md",
          "+The mapping schema is frozen at v0.2.",
          "+4. Never log, report, or raise a channel id that is not in the mapping.",
          "+5. SIGHUP must reload the map.",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "a08f3d91c2b74e0aa1d6f4c8e9b23170",
    short: "a08f3d9",
    author: { name: "Hovhannes Mkhitaryan", handle: "hovinthenorth" },
    date: "2026-09-10T03:46:00Z",
    message: "Publish the git as the page",
    body: "The repository is the public surface. No separate landing.",
    files: [
      {
        path: "README.md",
        status: "modified",
        additions: 4,
        deletions: 1,
        patch: [
          "@@ README.md",
          " Scoped human–agent relays.",
          "-",
          "+> The page is the git.",
          "+",
          " Agents should not be prompted into the right room. They should be **mapped** there.",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "5e2c710b8a91d33f0c17aa42e6d90bf1",
    short: "5e2c710",
    author: { name: "Grok", handle: "grok" },
    date: "2026-09-09T22:11:00Z",
    message: "Add Node runtime with the same wall",
    files: [
      {
        path: "agent/node/scope.ts",
        status: "added",
        additions: 28,
        deletions: 0,
        patch: [
          "@@ agent/node/scope.ts",
          "+export class ScopeGuard {",
          "+  allow(channelId: string): boolean {",
          "+    return this.ids.has(channelId);",
          "+  }",
          "+  require(channelId: string, action: string): void {",
          "+    if (!this.allow(channelId)) {",
          "+      throw new ScopeError(`blocked ${action} on ${channelId}`);",
          "+    }",
          "+  }",
          "+}",
        ].join("\n"),
      },
      {
        path: "agent/node/relay.ts",
        status: "added",
        additions: 48,
        deletions: 0,
        patch: [
          "@@ agent/node/relay.ts",
          "+const mapping = loadMapping(readFileSync(values.mapping, \"utf8\"));",
          "+const guard = new ScopeGuard(mapping);",
          "+if (values[\"dry-run\"]) adapter.describe();",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "1b9aa47e0d2c88f16a3b9e4c71f0a255",
    short: "1b9aa47",
    author: { name: "Grok", handle: "grok" },
    date: "2026-09-09T18:40:00Z",
    message: "Slack and Discord adapters, dry-run first",
    files: [
      {
        path: "agent/python/slack_adapter.py",
        status: "added",
        additions: 36,
        deletions: 0,
        patch: [
          "@@ agent/python/slack_adapter.py",
          "+class SlackAdapter:",
          "+    def describe(self, out: TextIO) -> None:",
          "+        out.write(f\"axiom {m.agent}  scope={m.scope}  platform=slack\\n\")",
          "+    def run(self, collect_seconds: int) -> None:",
          "+        for ch in self.mapping.channels:",
          "+            self.guard.require(ch.id, \"listen\")",
        ].join("\n"),
      },
      {
        path: "agent/python/discord_adapter.py",
        status: "added",
        additions: 32,
        deletions: 0,
        patch: [
          "@@ agent/python/discord_adapter.py",
          "+class DiscordAdapter:",
          "+    def run(self, collect_seconds: int) -> None:",
          "+        for ch in self.mapping.channels:",
          "+            self.guard.require(ch.id, \"listen\")",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "d4f06e3a91bb2c70e15d8a44c0f3e812",
    short: "d4f06e3",
    author: { name: "Hovhannes Mkhitaryan", handle: "hovinthenorth" },
    date: "2026-09-08T16:05:00Z",
    message: "Scope is a wall",
    body: "Unknown channel IDs are invisible. Crossing the wall is a bug.",
    files: [
      {
        path: "agent/python/scope.py",
        status: "added",
        additions: 24,
        deletions: 0,
        patch: [
          "@@ agent/python/scope.py",
          "+class ScopeGuard:",
          "+    def allow(self, channel_id: str) -> bool:",
          "+        return channel_id in self._ids",
          "+    def require(self, channel_id: str, action: str) -> None:",
          "+        if not self.allow(channel_id):",
          "+            raise ScopeError(",
          "+                f\"blocked {action} on {channel_id}: outside scope {self.scope!r}\"",
          "+            )",
        ].join("\n"),
      },
      {
        path: "agent/python/test_scope.py",
        status: "added",
        additions: 22,
        deletions: 0,
        patch: [
          "@@ agent/python/test_scope.py",
          "+def test_unknown_channel_is_invisible():",
          "+    assert guard.allow(\"C0OPS03\")",
          "+    assert not guard.allow(\"C0SECRET\")",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "7a12c88d04e91bf3a6c2d1e09aa44710",
    short: "7a12c88",
    author: { name: "Grok", handle: "grok" },
    date: "2026-09-07T20:18:00Z",
    message: "Parse mapping markdown as the only config",
    files: [
      {
        path: "agent/python/mapping.py",
        status: "added",
        additions: 110,
        deletions: 0,
        patch: [
          "@@ agent/python/mapping.py",
          "+def load_mapping(text: str) -> Mapping:",
          "+    meta, table = _split_front_matter(text)",
          "+    channels = _parse_table(table)",
          "+    _validate(meta, channels)",
        ].join("\n"),
      },
      {
        path: "schema/channels.md",
        status: "added",
        additions: 40,
        deletions: 0,
        patch: [
          "@@ schema/channels.md",
          "+# Channel mapping schema",
          "+A mapping is a markdown document. Agents must parse it, not invent a parallel config.",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "9e4b0d1c77a2f09e4b18c6d3a1f02590",
    short: "9e4b0d1",
    author: { name: "Hovhannes Mkhitaryan", handle: "hovinthenorth" },
    date: "2026-09-06T14:22:00Z",
    message: "Write the three axioms",
    files: [
      {
        path: "AXIOMS.md",
        status: "added",
        additions: 28,
        deletions: 0,
        patch: [
          "@@ AXIOMS.md",
          "+# Three axioms",
          "+## 01 — Map, don't prompt",
          "+## 02 — Relay, then report",
          "+## 03 — Scope is a wall",
        ].join("\n"),
      },
    ],
  },
  {
    hash: "c3a91f2e18d04bb7a90c1e5f2d8a6713",
    short: "c3a91f2",
    author: { name: "Hovhannes Mkhitaryan", handle: "hovinthenorth" },
    date: "2026-09-03T11:00:00Z",
    message: "Initial commit",
    files: [
      {
        path: "LICENSE",
        status: "added",
        additions: 21,
        deletions: 0,
        patch: ["@@ LICENSE", "+MIT License", "+Copyright (c) 2026 Hovhannes Mkhitaryan"].join("\n"),
      },
      {
        path: "README.md",
        status: "added",
        additions: 40,
        deletions: 0,
        patch: ["@@ README.md", "+# axiom", "+Scoped human–agent relays."].join("\n"),
      },
    ],
  },
];

export function commitByHash(hash: string): Commit | undefined {
  return COMMITS.find((c) => c.hash === hash || c.short === hash);
}

export function latestCommitFor(path: string): Commit | undefined {
  return COMMITS.find((c) =>
    c.files.some((f) => f.path === path || f.path.startsWith(path + "/") || path.startsWith(f.path)),
  );
}

export function fileCount(): number {
  return FILES.length;
}
