import type { RepoFile } from "./types";

const INIT = '"""Axiom scoped relay — Python runtime."""\n';

const RELAY = [
  '"""Axiom scoped relay.',
  "",
  "Reads a channel-mapping markdown file (path or https URL), then:",
  "  1. Listens on management channels (direction: in)",
  "  2. Fans broadcasts into scoped rooms",
  "  3. Collects replies and posts a report",
  "",
  "Scope is a wall. Channels not listed in the mapping are invisible.",
  "SIGHUP reloads the map without a restart.",
  '"""',
  "",
  "from __future__ import annotations",
  "",
  "import argparse",
  "import logging",
  "import signal",
  "import sys",
  "from pathlib import Path",
  "",
  "if __package__ is None:",
  "    sys.path.insert(0, str(Path(__file__).resolve().parent))",
  "",
  "from discord_adapter import DiscordAdapter",
  "from mapping import load_mapping_from",
  "from report import format_report",
  "from scope import ScopeGuard",
  "from slack_adapter import SlackAdapter",
  "",
  "ADAPTERS = {",
  '    "slack": SlackAdapter,',
  '    "discord": DiscordAdapter,',
  "}",
  "",
  "",
  "class Runtime:",
  "    def __init__(self, source: str, platform: str | None) -> None:",
  "        self.source = source",
  "        self.platform_override = platform",
  "        self.reload()",
  "",
  "    def reload(self) -> None:",
  "        mapping = load_mapping_from(self.source)",
  "        platform = self.platform_override or mapping.platform",
  "        if platform not in ADAPTERS:",
  '            raise SystemExit(f"unknown platform: {platform}")',
  "        self.mapping = mapping",
  "        self.platform = platform",
  "        self.guard = ScopeGuard(mapping)",
  "        self.adapter = ADAPTERS[platform](mapping, self.guard)",
  '        logging.info("loaded scope=%s ids=%d", mapping.scope, len(mapping.ids()))',
  "",
  "",
  "def main(argv: list[str] | None = None) -> int:",
  '    parser = argparse.ArgumentParser(prog="axiom-relay")',
  '    parser.add_argument("--mapping", required=True, help="path or https URL")',
  '    parser.add_argument("--platform", choices=sorted(ADAPTERS))',
  '    parser.add_argument("--dry-run", action="store_true")',
  '    parser.add_argument("--collect-seconds", type=int, default=None)',
  "    args = parser.parse_args(argv)",
  "",
  "    runtime = Runtime(args.mapping, args.platform)",
  "    collect = args.collect_seconds or runtime.mapping.collect_seconds",
  "",
  "    if args.dry_run:",
  "        runtime.adapter.describe(sys.stdout)",
  "        sys.stdout.write(format_report(",
  "            mapping=runtime.mapping,",
  "            guard=runtime.guard,",
  '            broadcast_id=runtime.mapping.by_role("management")[0].id,',
  "            reply_count=0,",
  "            collect_seconds=collect,",
  "        ))",
  "        return 0",
  "",
  "    if hasattr(signal, \"SIGHUP\"):",
  "        signal.signal(signal.SIGHUP, lambda *_: runtime.reload())",
  "",
  "    runtime.adapter.run(collect_seconds=collect)",
  "    return 0",
  "",
  "",
  'if __name__ == "__main__":',
  "    raise SystemExit(main())",
].join("\n");

const MAPPING = [
  '"""Parse an Axiom mapping markdown file (front matter + table)."""',
  "",
  "from __future__ import annotations",
  "",
  "from dataclasses import dataclass",
  "from pathlib import Path",
  "from urllib.request import Request, urlopen",
  "",
  "ROLES = {\"management\", \"room\", \"reports\"}",
  "DIRECTIONS = {\"in\", \"out\", \"both\"}",
  "PLATFORMS = {\"slack\", \"discord\"}",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Channel:",
  "    id: str",
  "    name: str",
  "    role: str",
  "    direction: str",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Mapping:",
  "    workspace: str",
  "    platform: str",
  "    scope: str",
  "    agent: str",
  "    collect_seconds: int",
  "    channels: tuple[Channel, ...]",
  "",
  "    def ids(self) -> set[str]:",
  "        return {c.id for c in self.channels}",
  "",
  "    def by_role(self, role: str) -> tuple[Channel, ...]:",
  "        return tuple(c for c in self.channels if c.role == role)",
  "",
  "",
  "class MappingError(ValueError):",
  "    pass",
  "",
  "",
  "def read_source(source: str) -> str:",
  '    if source.startswith(("http://", "https://")):',
  '        req = Request(source, headers={"User-Agent": "axiom-relay/0.2"})',
  "        with urlopen(req, timeout=15) as resp:",
  "            return resp.read().decode(\"utf-8\")",
  "    return Path(source).read_text(encoding=\"utf-8\")",
  "",
  "",
  "def load_mapping_from(source: str) -> Mapping:",
  "    return load_mapping(read_source(source))",
  "",
  "",
  "def load_mapping(text: str) -> Mapping:",
  "    meta, table = _split_front_matter(text)",
  "    channels = _parse_table(table)",
  "    _validate(meta, channels)",
  "    return Mapping(",
  '        workspace=meta["workspace"],',
  '        platform=meta["platform"],',
  '        scope=meta["scope"],',
  '        agent=meta["agent"],',
  '        collect_seconds=int(meta.get("collect_seconds", 45)),',
  "        channels=channels,",
  "    )",
  "",
  "",
  "def _split_front_matter(text: str) -> tuple[dict[str, str], str]:",
  '    if not text.startswith("---"):',
  '        raise MappingError("mapping must start with YAML front matter")',
  '    rest = text[3:]',
  '    end = rest.find("\\n---")',
  "    if end < 0:",
  '        raise MappingError("unterminated front matter")',
  "    raw, body = rest[:end], rest[end + 4 :]",
  "    meta: dict[str, str] = {}",
  "    for line in raw.splitlines():",
  '        if not line.strip() or ":" not in line:',
  "            continue",
  '        key, value = line.split(":", 1)',
  "        meta[key.strip()] = value.strip()",
  "    return meta, body",
  "",
  "",
  "def _parse_table(body: str) -> tuple[Channel, ...]:",
  "    rows: list[Channel] = []",
  "    header: list[str] | None = None",
  "    for raw in body.splitlines():",
  '        line = raw.strip()',
  '        if not line.startswith("|"):',
  "            continue",
  '        cells = [c.strip() for c in line.strip("|").split("|")]',
  '        if header is None:',
  "            header = [c.lower() for c in cells]",
  "            continue",
  '        if set("".join(cells)) <= set("-: "):',
  "            continue",
  "        data = dict(zip(header, cells))",
  "        rows.append(",
  "            Channel(",
  '                id=data["id"],',
  '                name=data.get("name", ""),',
  '                role=data["role"],',
  '                direction=data["direction"],',
  "            )",
  "        )",
  "    return tuple(rows)",
  "",
  "",
  "def _validate(meta: dict[str, str], channels: tuple[Channel, ...]) -> None:",
  '    for key in ("workspace", "platform", "scope", "agent"):',
  "        if not meta.get(key):",
  '            raise MappingError(f"missing {key}")',
  '    if meta["platform"] not in PLATFORMS:',
  '        raise MappingError(f"unknown platform {meta[\'platform\']!r}")',
  "    ids = [c.id for c in channels]",
  "    if len(ids) != len(set(ids)):",
  '        raise MappingError("duplicate channel id")',
  "    for ch in channels:",
  "        if ch.role not in ROLES:",
  '            raise MappingError(f"unknown role {ch.role!r}")',
  "        if ch.direction not in DIRECTIONS:",
  '            raise MappingError(f"unknown direction {ch.direction!r}")',
  '    if not any(c.role == "management" and c.direction in {"in", "both"} for c in channels):',
  '        raise MappingError("need a management channel with direction in/both")',
  '    if not any(c.role == "reports" and c.direction in {"out", "both"} for c in channels):',
  '        raise MappingError("need a reports channel with direction out/both")',
].join("\n");

const SCOPE = [
  '"""Scope is a wall. Adapters never see ids outside the mapping."""',
  "",
  "from __future__ import annotations",
  "",
  "import logging",
  "",
  "from mapping import Mapping",
  "",
  "",
  "class ScopeError(PermissionError):",
  "    pass",
  "",
  "",
  "class ScopeGuard:",
  "    def __init__(self, mapping: Mapping) -> None:",
  "        self.scope = mapping.scope",
  "        self._ids = mapping.ids()",
  "",
  "    def allow(self, channel_id: str) -> bool:",
  "        return channel_id in self._ids",
  "",
  "    def redact(self, channel_id: str) -> str:",
  '        return channel_id if self.allow(channel_id) else "<outside-scope>"',
  "",
  "    def require(self, channel_id: str, action: str) -> None:",
  "        if not self.allow(channel_id):",
  "            raise ScopeError(",
  '                f"blocked {action}: outside scope {self.scope!r}"',
  "            )",
  "",
  "    def drop(self, channel_id: str, reason: str) -> None:",
  "        # The raw id never leaves this function.",
  '        logging.info("dropped event source=<outside-scope> reason=%s", reason)',
].join("\n");

const REPORT = [
  '"""Single report shape. Filed to every reports channel, never to a room."""',
  "",
  "from __future__ import annotations",
  "",
  "from mapping import Mapping",
  "from scope import ScopeGuard",
  "",
  "",
  "def format_report(",
  "    *,",
  "    mapping: Mapping,",
  "    guard: ScopeGuard,",
  "    broadcast_id: str,",
  "    reply_count: int,",
  "    collect_seconds: int,",
  ") -> str:",
  '    guard.require(broadcast_id, "report")',
  "    rooms = mapping.by_role(\"room\")",
  "    reports = mapping.by_role(\"reports\")",
  "    lines = [",
  '        f"# report from {mapping.agent}",',
  '        f"scope: {mapping.scope}",',
  '        f"broadcast: {guard.redact(broadcast_id)}",',
  '        f"rooms: {len(rooms)}",',
  '        f"replies: {reply_count}",',
  '        f"window: {collect_seconds}s",',
  '        f"filed: {len(reports)} reports channel(s)",',
  "    ]",
  '    return "\\n".join(lines) + "\\n"',
].join("\n");

const SLACK = [
  '"""Slack adapter. Dry-run needs no SDK. Live import is deferred."""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import TextIO",
  "",
  "from mapping import Mapping",
  "from scope import ScopeGuard",
  "",
  "",
  "class SlackAdapter:",
  "    def __init__(self, mapping: Mapping, guard: ScopeGuard) -> None:",
  "        self.mapping = mapping",
  "        self.guard = guard",
  "",
  "    def describe(self, out: TextIO) -> None:",
  '        m = self.mapping',
  '        out.write(f"axiom {m.agent}  scope={m.scope}  platform=slack\\n")',
  "        for ch in m.channels:",
  '            out.write(f"  {ch.role:12} {ch.direction:4}  {ch.id}  {ch.name}\\n")',
  "        rooms = m.by_role(\"room\")",
  '        out.write(f"fan-out: {len(rooms)} room(s)  wall: {len(self.guard._ids)} id(s)\\n")',
  "",
  "    def run(self, collect_seconds: int) -> None:",
  "        for ch in self.mapping.channels:",
  '            self.guard.require(ch.id, "listen")',
  "        # Live path: slack_sdk WebClient + Socket Mode, filtered by guard.",
  '        raise SystemExit("live Slack requires SLACK_BOT_TOKEN and slack-sdk")',
].join("\n");

const DISCORD = [
  '"""Discord adapter. Same wall, different transport."""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import TextIO",
  "",
  "from mapping import Mapping",
  "from scope import ScopeGuard",
  "",
  "",
  "class DiscordAdapter:",
  "    def __init__(self, mapping: Mapping, guard: ScopeGuard) -> None:",
  "        self.mapping = mapping",
  "        self.guard = guard",
  "",
  "    def describe(self, out: TextIO) -> None:",
  "        m = self.mapping",
  '        out.write(f"axiom {m.agent}  scope={m.scope}  platform=discord\\n")',
  "        for ch in m.channels:",
  '            out.write(f"  {ch.role:12} {ch.direction:4}  {ch.id}  {ch.name}\\n")',
  '        out.write("unknown channel ids are dropped before on_message\\n")',
  "",
  "    def run(self, collect_seconds: int) -> None:",
  "        for ch in self.mapping.channels:",
  '            self.guard.require(ch.id, "listen")',
  '        raise SystemExit("live Discord requires DISCORD_BOT_TOKEN and discord.py")',
].join("\n");

const TEST_SCOPE = [
  "from mapping import load_mapping",
  "from scope import ScopeError, ScopeGuard",
  "",
  "SAMPLE = \"\"\"---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  '"""',
  "",
  "",
  "def test_unknown_channel_is_invisible():",
  "    mapping = load_mapping(SAMPLE)",
  "    guard = ScopeGuard(mapping)",
  "    assert guard.allow(\"C0OPS03\")",
  "    assert not guard.allow(\"C0SECRET\")",
  "    try:",
  '        guard.require("C0SECRET", "write")',
  "        raise AssertionError(\"wall failed\")",
  "    except ScopeError as err:",
  "        assert \"C0SECRET\" not in str(err)",
  "",
  "",
  "def test_redact_does_not_echo_unknown_id():",
  "    guard = ScopeGuard(load_mapping(SAMPLE))",
  '    assert guard.redact("C0OPS03") == "C0OPS03"',
  '    assert guard.redact("C0SECRET") == "<outside-scope>"',
  "",
  "",
  'if __name__ == "__main__":',
  "    test_unknown_channel_is_invisible()",
  "    test_redact_does_not_echo_unknown_id()",
  '    print("ok")',
].join("\n");

const TEST_MAPPING = [
  "from mapping import MappingError, load_mapping",
  "",
  "",
  "def test_missing_management_is_an_error():",
  "    text = \"\"\"---",
  "workspace: x",
  "platform: slack",
  "scope: team.x",
  "agent: r",
  "---",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C1 | #r | reports | out |",
  '"""',
  "    try:",
  "        load_mapping(text)",
  "        raise AssertionError(\"accepted a map with no management channel\")",
  "    except MappingError:",
  "        pass",
  "",
  "",
  'if __name__ == "__main__":',
  "    test_missing_management_is_an_error()",
  '    print("ok")',
].join("\n");

const REQUIREMENTS = [
  "# stdlib is enough for dry-run, URL maps, and mapping tests.",
  "# Live adapters (optional):",
  "# slack-sdk>=3.33",
  "# discord.py>=2.4",
  "",
].join("\n");

export const PYTHON_FILES: RepoFile[] = [
  { path: "agent/python/__init__.py", language: "python", content: INIT },
  { path: "agent/python/relay.py", language: "python", content: RELAY + "\n" },
  { path: "agent/python/mapping.py", language: "python", content: MAPPING + "\n" },
  { path: "agent/python/scope.py", language: "python", content: SCOPE + "\n" },
  { path: "agent/python/report.py", language: "python", content: REPORT + "\n" },
  { path: "agent/python/slack_adapter.py", language: "python", content: SLACK + "\n" },
  { path: "agent/python/discord_adapter.py", language: "python", content: DISCORD + "\n" },
  { path: "agent/python/test_scope.py", language: "python", content: TEST_SCOPE + "\n" },
  { path: "agent/python/test_mapping.py", language: "python", content: TEST_MAPPING + "\n" },
  { path: "agent/python/requirements.txt", language: "text", content: REQUIREMENTS },
];
