import type { RepoFile } from "./types";

const MAPPING = [
  "---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "collect_seconds: 45",
  "---",
  "",
  "# growth-chef / team.growth",
  "",
  "Fictional IDs. Replace with your own. Names are documentation; routing uses `id` only.",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  "| C0LAUNCH | #launch | room | both |",
].join("\n");

const DISCORD = [
  "---",
  "workspace: growth-chef",
  "platform: discord",
  "scope: team.growth",
  "agent: relay-prime",
  "collect_seconds: 45",
  "---",
  "",
  "# growth-chef / team.growth  (Discord)",
  "",
  "Same topology as `mapping.md`. Different snowflakes. Same wall.",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| 140000000000000001 | mgmt | management | in |",
  "| 140000000000000002 | reports | reports | out |",
  "| 140000000000000003 | ops | room | both |",
  "| 140000000000000004 | launch | room | both |",
].join("\n");

const LOCAL = [
  "mapping: examples/mapping.md",
  "platform: slack",
  "dry_run: true",
  "collect_seconds: 45",
].join("\n");

const WORK = [
  "---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "collect_seconds: 45",
  "---",
  "",
  "# growth-chef / team.growth — broadcasts as projects",
  "",
  "Fictional IDs. The `work` table is what Notion dumps. The `channels` table is the wall.",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  "| C0LAUNCH | #launch | room | both |",
  "",
  "| id | name | room | state | anchor | owner |",
  "|----|------|------|-------|--------|-------|",
  "| north-star | North Star launch | C0OPS03 | active | | U08AAAA |",
  "| beta-waitlist | Beta waitlist | C0LAUNCH | active | 1000000000.000001 | U06BBBB |",
  "| no-room | Unmapped work | C0GHOST | active | | U06CCCC |",
].join("\n");

const TRAIL = [
  "# report from relay-prime",
  "scope: team.growth",
  "work: 3  post: 0  gather: 2  skip: 0  gaps: 1",
  "",
  "## north-star — active",
  "room: C0OPS03",
  "owner: U08AAAA",
  "anchor: 1000000000.000002",
  "action: gather",
  "trail:",
  "  - Jordan Lee: legal copy is in the shared doc  [https://example.slack.com/archives/C0OPS03/p1789405300]",
  "  - <unresolved:U0NONE01>: thank you  [https://example.slack.com/archives/C0OPS03/p1789405412]",
  "",
  "## beta-waitlist — active",
  "room: C0LAUNCH",
  "owner: U06BBBB",
  "anchor: 1000000000.000001",
  "action: gather",
  "trail: silent (read this thread; do not open another)",
  "",
  "## no-room — active",
  "gaps: room not in map",
  "",
  "Notes (not part of a live report):",
  "",
  "- The first crumb has a resolved name and a permalink. It renders.",
  "- The second crumb has no resolved name. It stays `<unresolved:…>`. It was not guessed.",
  "- `beta-waitlist` had an anchor and no new replies. Silence is recorded.",
  "- `no-room` is a gap. No channel was invented.",
].join("\n");

export const EXAMPLE_FILES: RepoFile[] = [
  { path: "examples/mapping.md", language: "markdown", content: MAPPING + "\n" },
  { path: "examples/discord.md", language: "markdown", content: DISCORD + "\n" },
  { path: "examples/mapping-work.md", language: "markdown", content: WORK + "\n" },
  { path: "examples/trail.md", language: "markdown", content: TRAIL + "\n" },
  { path: "examples/local.yaml", language: "yaml", content: LOCAL + "\n" },
];
