import type { RepoFile } from "./types";

const README = [
  "# axiom",
  "",
  "Scoped human–agent relays.",
  "",
  "> The page is the git.",
  "",
  "Agents should not be prompted into the right room. They should be **mapped** there.",
  "Axiom is a tiny protocol: a markdown file of Slack or Discord channel IDs, a scoped",
  "relay that reads it, and a wall that the agent cannot climb.",
  "",
  "## Axioms",
  "",
  "1. **Map, don't prompt.** Channel IDs live in a markdown file. A cloud or local agent reads that file as the only source of truth for where it may speak.",
  "2. **Relay, then report.** Management channels broadcast. The agent fans the message into scoped rooms, collects replies, and reports back. Nothing else.",
  "3. **Scope is a wall.** An agent bound to `team.growth` cannot read, write, or even name a channel outside that scope.",
  "",
  "See [AXIOMS.md](/blob/AXIOMS.md) and [PROTOCOL.md](/blob/PROTOCOL.md).",
  "",
  "## Tree",
  "",
  "```",
  "scoped-relay/",
  "  PROTOCOL.md        # frozen contract",
  "  agent/",
  "    python/          # stdlib relay + Slack/Discord adapters",
  "    node/            # TypeScript port, same contract",
  "  schema/            # mapping markdown spec + JSON Schema",
  "  examples/          # slack + discord mappings, plus work/broadcasts",
  "  docs/",
  "```",
  "",
  "## Quick start",
  "",
  "Local, no tokens — prove the map parses and the wall holds:",
  "",
  "```bash",
  "python agent/python/relay.py --mapping examples/mapping.md --dry-run",
  "```",
  "",
  "or",
  "",
  "```bash",
  "npx tsx agent/node/relay.ts --mapping examples/mapping.md --dry-run",
  "```",
  "",
  "The mapping may be a path or an `https://` URL. `SIGHUP` reloads it.",
  "",
  "Live Slack:",
  "",
  "```bash",
  "export SLACK_BOT_TOKEN=xoxb-...",
  "python agent/python/relay.py --mapping examples/mapping.md --platform slack",
  "```",
  "",
  "Live Discord:",
  "",
  "```bash",
  "export DISCORD_BOT_TOKEN=...",
  "python agent/python/relay.py --mapping examples/mapping.md --platform discord",
  "```",
  "",
  "The same mapping file runs in the cloud. Point a long-lived process (systemd, Fly, a tiny VM) at the markdown. That is the whole deploy.",
  "",
  "## Mapping",
  "",
  "A mapping is YAML front matter plus one or two tables. The agent reads it on boot and on every `SIGHUP`.",
  "",
  "```md",
  "---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  "```",
  "",
  "- `management` / `in` — broadcasts originate here.",
  "- `room` — scoped destinations. The agent may speak here only because the row exists.",
  "- `reports` / `out` — collected replies are posted here.",
  "",
  "Optional second table — **work** — maps each broadcast to a project and a room:",
  "",
  "```md",
  "| id | name | room | state | anchor | owner |",
  "|----|------|------|-------|--------|-------|",
  "| north-star | North Star launch | C0OPS03 | active | | U08AAAA |",
  "```",
  "",
  "Notion (or any PM) dumps this table. The relay reads markdown. See [examples/mapping-work.md](/blob/examples/mapping-work.md).",
  "Info gathering along a posted broadcast: [docs/breadcrumb.md](/blob/docs/breadcrumb.md).",
  "",
  "Full contract: [schema/channels.md](/blob/schema/channels.md).",
  "",
  "## License",
  "",
  "MIT. Use it, fork it, host the git as a page.",
].join("\n");

const AXIOMS = [
  "# Three axioms",
  "",
  "Human–agent communication fails in the same place every time: the agent is asked to *figure out* where it belongs. Axiom inverts that. Belonging is data.",
  "",
  "## 01 — Map, don't prompt",
  "",
  "Slack or Discord channel mappings are simple IDs. They live in a markdown file. A cloud or local agent reads this file. The file is the permission set, the topology, and the documentation.",
  "",
  "If a channel is not a row, it does not exist.",
  "",
  "## 02 — Relay, then report",
  "",
  "Management channels broadcast. The agent relays that broadcast into every room inside the same scope, waits, collects what comes back, and files a report. It does not chat. It does not opine. It does not join a new room because a message *mentioned* one.",
  "",
  "## 03 — Scope is a wall",
  "",
  "Scope is not a suggestion and not a system prompt. It is enforced in code before any adapter call. An event for a channel outside the mapping is dropped, logged without the raw id, and never named in a report. Crossing the wall is a bug, not a feature.",
  "",
  "---",
  "",
  "That is the whole protocol. The rest of this repository is a faithful implementation.",
].join("\n");

const PROTOCOL = [
  "# PROTOCOL",
  "",
  "Frozen at v0.3. v0.2 maps load unchanged. Implementations may add platforms. They may not add curiosity.",
  "",
  "## Changelog",
  "",
  "- **v0.3** — optional `work` table. Each row is one broadcast, joined to a mapped room. Notion (or any PM) may *materialize* this table; the relay still only reads markdown. An existing `anchor` is a gather, not a skip: read that thread, cite permalinks, do not open a second.",
  "- **v0.2** — path or `https://` mapping, SIGHUP reload, unknown ids redacted.",
  "",
  "## 1. Mapping",
  "",
  "A mapping is a markdown document: YAML front matter + **one or two tables**. It is the only config.",
  "",
  "Source: a filesystem path **or** an `https://` URL. The agent does not fetch anything else.",
  "A provider (Notion, a database) may write the file. It never becomes the parse target.",
  "",
  "Required front matter: `workspace`, `platform` (`slack` | `discord`), `scope`, `agent`.",
  "Optional: `collect_seconds` (default `45`).",
  "",
  "The first table is `channels`. Required columns: `id`, `name`, `role`, `direction`.",
  "",
  "`name` is documentation. Routing uses `id` only.",
  "",
  "### Work (optional)",
  "",
  "A second table, detected by columns `room` + `state`. Each row is a **broadcast** — one unit of work, one room.",
  "",
  "| column | required | notes |",
  "|--------|----------|-------|",
  "| `id` | yes | Stable project key. Never reused. |",
  "| `name` | yes | Documentation. |",
  "| `room` | yes | Must be a `room`-role id in `channels`. Else: **gap**. |",
  "| `state` | yes | `active` · `blocked` · `closed` |",
  "| `anchor` | no | Platform thread id. Empty → **post** once and record it. Present → **gather** that thread. Never a second anchor. |",
  "| `owner` | no | Human. Documentation. |",
  "",
  "A v0.2 file with no work table is valid. The relay then fans out as before.",
  "",
  "## 2. Roles",
  "",
  "| role | speaks | listens |",
  "|------|--------|---------|",
  "| `management` | never, unless `both` | broadcasts (`in` / `both`) |",
  "| `room` | fan-out of a broadcast | replies during the collect window |",
  "| `reports` | the filed report (`out` / `both`) | never |",
  "",
  "A map without a management `in`/`both` row, or without a reports `out`/`both` row, is invalid.",
  "",
  "## 3. The wall",
  "",
  "`ScopeGuard.allow(id)` is called before every read and every write.",
  "",
  "- Unknown ids are dropped before the adapter sees the event.",
  "- Logs and exceptions substitute `<outside-scope>`. The raw id is not interpolated.",
  "- Reports may only name ids that `allow` returns true for.",
  "",
  "A second workspace is a second process with a second file. Not a smarter prompt.",
  "",
  "## 4. Relay, then report",
  "",
  "1. Event arrives from a management channel — or a cadence reads the `work` table.",
  "2. Guard checks every id involved.",
  "3. Without a work table: fan-out to every `room` in the map, excluding the source.",
  "   With a work table: one post per row with no `anchor`. Rows with an `anchor` **gather** that thread — they do not post again.",
  "4. Collect is a breadcrumb trail: replies *under the anchor only*. See [docs/breadcrumb.md](/blob/docs/breadcrumb.md).",
  "5. One report, posted to every `reports` channel.",
  "",
  "Report shape (v0.2, no work table):",
  "",
  "```",
  "# report from {agent}",
  "scope: {scope}",
  "broadcast: {id}",
  "rooms: {n}",
  "replies: {n}",
  "window: {seconds}s",
  "filed: {n} reports channel(s)",
  "```",
  "",
  "Report shape (v0.3, work table):",
  "",
  "```",
  "# report from {agent}",
  "scope: {scope}",
  "work: {n}  post: {n}  gather: {n}  skip: {n}  gaps: {n}",
  "",
  "## {work.id} — {state}",
  "room: {id}",
  "anchor: {ts}",
  "action: gather",
  "trail:",
  "  - {name}: {claim}  [{permalink}]",
  "  - <unresolved:{id}>: {claim}  [{permalink}]",
  "```",
  "",
  "A crumb without a permalink does not render. An unresolved author is never named.",
  "",
  "## 5. Reload",
  "",
  "`SIGHUP` re-reads the mapping source and rebuilds the wall. No restart. No drain of in-flight collect windows — they finish against the map they started with.",
  "",
  "## 6. Failure",
  "",
  "Fail closed. A parse error, a missing token, an unknown platform, a duplicate `work.id` — exit non-zero.",
  "A work row whose room is not in `channels` is **not** fatal: it is a reported gap. Other rows still run.",
].join("\n");

const LICENSE = [
  "MIT License",
  "",
  "Copyright (c) 2026 Hovhannes Mkhitaryan",
  "",
  "Permission is hereby granted, free of charge, to any person obtaining a copy",
  "of this software and associated documentation files (the \"Software\"), to deal",
  "in the Software without restriction, including without limitation the rights",
  "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
  "copies of the Software, and to permit persons to whom the Software is",
  "furnished to do so, subject to the following conditions:",
  "",
  "The above copyright notice and this permission notice shall be included in all",
  "copies or substantial portions of the Software.",
  "",
  "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
  "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
  "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
  "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
  "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
  "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
  "SOFTWARE.",
].join("\n");

const CONTRIBUTING = [
  "# Contributing",
  "",
  "The mapping schema is frozen at v0.3. v0.2 maps remain valid. New platforms are welcome if they implement the same three roles (`management`, `room`, `reports`) and fail closed on unknown channel IDs.",
  "",
  "1. Add an adapter next to `slack` / `discord`.",
  "2. Keep dry-run working without extra packages.",
  "3. Put a row in `examples/` only if it is fictional. No real names, user ids, channel ids, or brand names.",
  "4. Never log, report, or raise a channel id that is not in the mapping. Use `<outside-scope>`.",
  "5. `SIGHUP` must reload the map. Do not require a restart to add a channel.",
  "6. A work row may only broadcast into a mapped `room`. A missing room is a gap, never a guess.",
  "7. If `anchor` is set, do not open a second thread. Gather that thread instead.",
  "8. A breadcrumb crumb without a permalink does not render. Do not invent a name.",
].join("\n");

const SETUP = [
  "# Setup",
  "",
  "## Local",
  "",
  "Python 3.11+ or Node 22. No packages required for `--dry-run`.",
  "",
  "```bash",
  "python agent/python/relay.py --mapping examples/mapping.md --dry-run",
  "```",
  "",
  "Dry-run prints the parsed mapping, the scope wall, and a sample report. It does not open a socket.",
  "",
  "## Source",
  "",
  "`--mapping` is a path or an `https://` URL:",
  "",
  "```bash",
  "python agent/python/relay.py --mapping https://example.com/team.growth.md --dry-run",
  "```",
  "",
  "## Cloud",
  "",
  "Run the same command without `--dry-run` as a long-lived process. Reload the map with `SIGHUP`. Do not restart to add a channel.",
  "",
  "## Tokens",
  "",
  "| Variable | Used by |",
  "|----------|---------|",
  "| `SLACK_BOT_TOKEN` | Slack adapter |",
  "| `DISCORD_BOT_TOKEN` | Discord adapter |",
  "",
  "Tokens never live in the mapping file.",
].join("\n");

const SCOPED = [
  "# Scoped relays",
  "",
  "A scoped relay has a single mapping, a single scope string, and zero curiosity.",
  "",
  "## The wall",
  "",
  "`ScopeGuard.allow(channel_id)` is called before every read and every write. Adapters do not get a chance to be clever. If you need a second workspace, you run a second process with a second markdown file.",
  "",
  "Unknown ids are not logged. `redact()` returns `<outside-scope>`. Exceptions do not echo the raw id.",
  "",
  "## Broadcast plan",
  "",
  "1. Event arrives from a `management` channel with `direction` `in` or `both`.",
  "2. Guard checks the source id.",
  "3. Fan-out targets every `room` in the same mapping, excluding the source.",
  "4. Collect window (default 45s) gathers replies from those rooms only.",
  "5. A single report is posted to every `reports` channel.",
  "",
  "Unknown ids are dropped before step 2.",
  "",
  "With a `work` table the fan-out is per project. An existing `anchor` is a **gather**:",
  "read that thread, cite replies, do not post a second kickoff. Instructions:",
  "[docs/breadcrumb.md](/blob/docs/breadcrumb.md).",
  "",
  "## Reload",
  "",
  "`SIGHUP` rebuilds the mapping and the wall. In-flight collect windows finish against the map they started with.",
].join("\n");

const BREADCRUMB = [
  "# Breadcrumb trail",
  "",
  "A broadcast is a trail, not a blast. Info gathering follows one thread, in one room, for the life of the work.",
  "",
  "## When to post vs gather",
  "",
  "| `work.anchor` | action |",
  "|---------------|--------|",
  "| empty | **post** the ask once, record the thread id back onto the row |",
  "| set | **gather** — read that thread. Do not open a second |",
  "| row has no mapped `room` | **gap** — report it, do not guess a channel |",
  "| `state: closed` | **skip** |",
  "",
  "A second anchor is a bug, not a retry.",
  "",
  "## How to gather",
  "",
  "1. Guard every id. Unknown sources are `<outside-scope>` and never named.",
  "2. Read replies **under the anchor only**. Sibling messages in the same room are not on this trail.",
  "3. Each reply is a crumb, or it is omitted:",
  "",
  "```",
  "  - {resolved name}: {claim}  [{permalink}]",
  "  - <unresolved:{id}>: {claim}  [{permalink}]",
  "```",
  "",
  "4. Hard rules:",
  "   - No permalink → the line does not render. Do not paraphrase it in.",
  "   - Name lookup failed or rate-limited → `<unresolved:{id}>`. Never guess from context, nickname, or \"the team\".",
  "   - No new replies → `trail: silent`. Silence is data. Do not fill it.",
  "5. File the trail to `reports`. Do not fan crumbs back into rooms.",
  "",
  "## Live shape",
  "",
  "See [examples/trail.md](/blob/examples/trail.md) for a filled report. Dry-run prints the plan with empty trails; it does not invent crumbs.",
  "",
  "## What this is not",
  "",
  "Not a summary. Not a ranking. Not sentiment. The relay moves cited text and counts silence.",
].join("\n");

const GITIGNORE = [
  "__pycache__/",
  "*.pyc",
  ".venv/",
  "node_modules/",
  ".env",
  ".DS_Store",
  "dist/",
].join("\n");

const WORKFLOW = [
  "name: mapping-dry-run",
  "on: [push]",
  "jobs:",
  "  python:",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "      - uses: actions/setup-python@v5",
  "        with:",
  "          python-version: \"3.12\"",
  "      - run: python agent/python/test_scope.py",
  "      - run: python agent/python/test_mapping.py",
  "      - run: python agent/python/test_report.py",
  "      - run: python agent/python/relay.py --mapping examples/mapping.md --dry-run",
  "      - run: python agent/python/relay.py --mapping examples/mapping-work.md --dry-run",
  "  node:",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: \"22\"",
  "      - run: npx tsx agent/node/relay.ts --mapping examples/mapping.md --dry-run",
].join("\n");

export const DOC_FILES: RepoFile[] = [
  { path: "README.md", language: "markdown", content: README },
  { path: "AXIOMS.md", language: "markdown", content: AXIOMS },
  { path: "PROTOCOL.md", language: "markdown", content: PROTOCOL },
  { path: "LICENSE", language: "text", content: LICENSE },
  { path: "CONTRIBUTING.md", language: "markdown", content: CONTRIBUTING },
  { path: "docs/setup.md", language: "markdown", content: SETUP },
  { path: "docs/scoped-relays.md", language: "markdown", content: SCOPED },
  { path: "docs/breadcrumb.md", language: "markdown", content: BREADCRUMB },
  { path: ".gitignore", language: "ignore", content: GITIGNORE },
  { path: ".github/workflows/dry-run.yml", language: "yaml", content: WORKFLOW },
];
