import type { RepoFile } from "./types";

const README = [
  "# axiom",
  "",
  "Scoped human–agent relays.",
  "",
  "> The page is the git.",
  "",
  "Agents should not be prompted into the right room. They should be **mapped** there.",
  "Axiom is a tiny protocol: a markdown file of Slack or Discord channel IDs, a scoped",
  "relay that reads it, and a wall that the agent cannot climb.",
  "",
  "## Axioms",
  "",
  "1. **Map, don't prompt.** Channel IDs live in a markdown file. A cloud or local agent reads that file as the only source of truth for where it may speak.",
  "2. **Relay, then report.** Management channels broadcast. The agent fans the message into scoped rooms, collects replies, and reports back. Nothing else.",
  "3. **Scope is a wall.** An agent bound to `team.growth` cannot read, write, or even name a channel outside that scope.",
  "",
  "See [AXIOMS.md](/blob/AXIOMS.md) and [PROTOCOL.md](/blob/PROTOCOL.md).",
  "",
  "## Tree",
  "",
  "```",
  "scoped-relay/",
  "  PROTOCOL.md        # frozen contract",
  "  agent/",
  "    python/          # stdlib relay + Slack/Discord adapters",
  "    node/            # TypeScript port, same contract",
  "  schema/            # mapping markdown spec + JSON Schema",
  "  examples/          # slack + discord mappings",
  "  docs/",
  "```",
  "",
  "## Quick start",
  "",
  "Local, no tokens — prove the map parses and the wall holds:",
  "",
  "```bash",
  "python agent/python/relay.py --mapping examples/mapping.md --dry-run",
  "```",
  "",
  "or",
  "",
  "```bash",
  "npx tsx agent/node/relay.ts --mapping examples/mapping.md --dry-run",
  "```",
  "",
  "The mapping may be a path or an `https://` URL. `SIGHUP` reloads it.",
  "",
  "Live Slack:",
  "",
  "```bash",
  "export SLACK_BOT_TOKEN=xoxb-...",
  "python agent/python/relay.py --mapping examples/mapping.md --platform slack",
  "```",
  "",
  "Live Discord:",
  "",
  "```bash",
  "export DISCORD_BOT_TOKEN=...",
  "python agent/python/relay.py --mapping examples/mapping.md --platform discord",
  "```",
  "",
  "The same mapping file runs in the cloud. Point a long-lived process (systemd, Fly, a tiny VM) at the markdown. That is the whole deploy.",
  "",
  "## Mapping",
  "",
  "A mapping is YAML front matter plus one table. The agent reads it on boot and on every `SIGHUP`.",
  "",
  "```md",
  "---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  "```",
  "",
  "- `management` / `in` — broadcasts originate here.",
  "- `room` — scoped destinations. The agent may speak here only because the row exists.",
  "- `reports` / `out` — collected replies are posted here.",
  "",
  "Full contract: [schema/channels.md](/blob/schema/channels.md).",
  "",
  "## License",
  "",
  "MIT. Use it, fork it, host the git as a page.",
].join("\n");

const AXIOMS = [
  "# Three axioms",
  "",
  "Human–agent communication fails in the same place every time: the agent is asked to *figure out* where it belongs. Axiom inverts that. Belonging is data.",
  "",
  "## 01 — Map, don't prompt",
  "",
  "Slack or Discord channel mappings are simple IDs. They live in a markdown file. A cloud or local agent reads this file. The file is the permission set, the topology, and the documentation.",
  "",
  "If a channel is not a row, it does not exist.",
  "",
  "## 02 — Relay, then report",
  "",
  "Management channels broadcast. The agent relays that broadcast into every room inside the same scope, waits, collects what comes back, and files a report. It does not chat. It does not opine. It does not join a new room because a message *mentioned* one.",
  "",
  "## 03 — Scope is a wall",
  "",
  "Scope is not a suggestion and not a system prompt. It is enforced in code before any adapter call. An event for a channel outside the mapping is dropped, logged without the raw id, and never named in a report. Crossing the wall is a bug, not a feature.",
  "",
  "---",
  "",
  "That is the whole protocol. The rest of this repository is a faithful implementation.",
].join("\n");

const PROTOCOL = [
  "# PROTOCOL",
  "",
  "Frozen at v0.2. Implementations may add platforms. They may not add curiosity.",
  "",
  "## 1. Mapping",
  "",
  "A mapping is a markdown document: YAML front matter + one table. It is the only config.",
  "",
  "Source: a filesystem path **or** an `https://` URL. The agent does not fetch anything else.",
  "",
  "Required front matter: `workspace`, `platform` (`slack` | `discord`), `scope`, `agent`.",
  "Optional: `collect_seconds` (default `45`).",
  "",
  "Required columns: `id`, `name`, `role`, `direction`.",
  "",
  "`name` is documentation. Routing uses `id` only.",
  "",
  "## 2. Roles",
  "",
  "| role | speaks | listens |",
  "|------|--------|---------|",
  "| `management` | never, unless `both` | broadcasts (`in` / `both`) |",
  "| `room` | fan-out of a broadcast | replies during the collect window |",
  "| `reports` | the filed report (`out` / `both`) | never |",
  "",
  "A map without a management `in`/`both` row, or without a reports `out`/`both` row, is invalid.",
  "",
  "## 3. The wall",
  "",
  "`ScopeGuard.allow(id)` is called before every read and every write.",
  "",
  "- Unknown ids are dropped before the adapter sees the event.",
  "- Logs and exceptions substitute `<outside-scope>`. The raw id is not interpolated.",
  "- Reports may only name ids that `allow` returns true for.",
  "",
  "A second workspace is a second process with a second file. Not a smarter prompt.",
  "",
  "## 4. Relay, then report",
  "",
  "1. Event arrives from a management channel.",
  "2. Guard checks the source id.",
  "3. Fan-out to every `room` in the map, excluding the source.",
  "4. Collect window gathers replies from those rooms only.",
  "5. One report, posted to every `reports` channel.",
  "",
  "Report shape (v0.2):",
  "",
  "```",
  "# report from {agent}",
  "scope: {scope}",
  "broadcast: {id}",
  "rooms: {n}",
  "replies: {n}",
  "window: {seconds}s",
  "filed: {n} reports channel(s)",
  "```",
  "",
  "## 5. Reload",
  "",
  "`SIGHUP` re-reads the mapping source and rebuilds the wall. No restart. No drain of in-flight collect windows — they finish against the map they started with.",
  "",
  "## 6. Failure",
  "",
  "Fail closed. A parse error, a missing token, an unknown platform — exit non-zero. Do not run half a map.",
].join("\n");

const LICENSE = [
  "MIT License",
  "",
  "Copyright (c) 2026 Hovhannes Mkhitaryan",
  "",
  "Permission is hereby granted, free of charge, to any person obtaining a copy",
  "of this software and associated documentation files (the \"Software\"), to deal",
  "in the Software without restriction, including without limitation the rights",
  "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
  "copies of the Software, and to permit persons to whom the Software is",
  "furnished to do so, subject to the following conditions:",
  "",
  "The above copyright notice and this permission notice shall be included in all",
  "copies or substantial portions of the Software.",
  "",
  "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR",
  "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
  "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
  "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
  "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,",
  "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
  "SOFTWARE.",
].join("\n");

const CONTRIBUTING = [
  "# Contributing",
  "",
  "The mapping schema is frozen at v0.2. New platforms are welcome if they implement the same three roles (`management`, `room`, `reports`) and fail closed on unknown channel IDs.",
  "",
  "1. Add an adapter next to `slack` / `discord`.",
  "2. Keep dry-run working without extra packages.",
  "3. Put a row in `examples/` only if it is fictional.",
  "4. Never log, report, or raise a channel id that is not in the mapping. Use `<outside-scope>`.",
  "5. `SIGHUP` must reload the map. Do not require a restart to add a channel.",
].join("\n");

const SETUP = [
  "# Setup",
  "",
  "## Local",
  "",
  "Python 3.11+ or Node 22. No packages required for `--dry-run`.",
  "",
  "```bash",
  "python agent/python/relay.py --mapping examples/mapping.md --dry-run",
  "```",
  "",
  "Dry-run prints the parsed mapping, the scope wall, and a sample report. It does not open a socket.",
  "",
  "## Source",
  "",
  "`--mapping` is a path or an `https://` URL:",
  "",
  "```bash",
  "python agent/python/relay.py --mapping https://example.com/team.growth.md --dry-run",
  "```",
  "",
  "## Cloud",
  "",
  "Run the same command without `--dry-run` as a long-lived process. Reload the map with `SIGHUP`. Do not restart to add a channel.",
  "",
  "## Tokens",
  "",
  "| Variable | Used by |",
  "|----------|---------|",
  "| `SLACK_BOT_TOKEN` | Slack adapter |",
  "| `DISCORD_BOT_TOKEN` | Discord adapter |",
  "",
  "Tokens never live in the mapping file.",
].join("\n");

const SCOPED = [
  "# Scoped relays",
  "",
  "A scoped relay has a single mapping, a single scope string, and zero curiosity.",
  "",
  "## The wall",
  "",
  "`ScopeGuard.allow(channel_id)` is called before every read and every write. Adapters do not get a chance to be clever. If you need a second workspace, you run a second process with a second markdown file.",
  "",
  "Unknown ids are not logged. `redact()` returns `<outside-scope>`. Exceptions do not echo the raw id.",
  "",
  "## Broadcast plan",
  "",
  "1. Event arrives from a `management` channel with `direction` `in` or `both`.",
  "2. Guard checks the source id.",
  "3. Fan-out targets every `room` in the same mapping, excluding the source.",
  "4. Collect window (default 45s) gathers replies from those rooms only.",
  "5. A single report is posted to every `reports` channel.",
  "",
  "Unknown ids are dropped before step 2.",
  "",
  "## Reload",
  "",
  "`SIGHUP` rebuilds the mapping and the wall. In-flight collect windows finish against the map they started with.",
].join("\n");

const GITIGNORE = [
  "__pycache__/",
  "*.pyc",
  ".venv/",
  "node_modules/",
  ".env",
  ".DS_Store",
  "dist/",
].join("\n");

const WORKFLOW = [
  "name: mapping-dry-run",
  "on: [push]",
  "jobs:",
  "  python:",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "      - uses: actions/setup-python@v5",
  "        with:",
  "          python-version: \"3.12\"",
  "      - run: python agent/python/test_scope.py",
  "      - run: python agent/python/test_mapping.py",
  "      - run: python agent/python/relay.py --mapping examples/mapping.md --dry-run",
  "  node:",
  "    runs-on: ubuntu-latest",
  "    steps:",
  "      - uses: actions/checkout@v4",
  "      - uses: actions/setup-node@v4",
  "        with:",
  "          node-version: \"22\"",
  "      - run: npx tsx agent/node/relay.ts --mapping examples/mapping.md --dry-run",
].join("\n");

export const DOC_FILES: RepoFile[] = [
  { path: "README.md", language: "markdown", content: README },
  { path: "AXIOMS.md", language: "markdown", content: AXIOMS },
  { path: "PROTOCOL.md", language: "markdown", content: PROTOCOL },
  { path: "LICENSE", language: "text", content: LICENSE },
  { path: "CONTRIBUTING.md", language: "markdown", content: CONTRIBUTING },
  { path: "docs/setup.md", language: "markdown", content: SETUP },
  { path: "docs/scoped-relays.md", language: "markdown", content: SCOPED },
  { path: ".gitignore", language: "ignore", content: GITIGNORE },
  { path: ".github/workflows/dry-run.yml", language: "yaml", content: WORKFLOW },
];
