import type { RepoFile } from "./types";

const RELAY = [
  "#!/usr/bin/env npx tsx",
  "/** Axiom scoped relay — TypeScript runtime. Same contract as the Python agent. */",
  "",
  "import { parseArgs } from \"node:util\";",
  "import { loadMappingFrom, plan } from \"./mapping.ts\";",
  "import { formatReport } from \"./report.ts\";",
  "import { ScopeGuard } from \"./scope.ts\";",
  "import { SlackAdapter } from \"./slack.ts\";",
  "import { DiscordAdapter } from \"./discord.ts\";",
  "import { applyWrites, clientFromEnv, loadWorkFromNotion, NotionError } from \"./notion.ts\";",
  "",
  "const adapters = { slack: SlackAdapter, discord: DiscordAdapter } as const;",
  "",
  "class Runtime {",
  "  mapping!: Awaited<ReturnType<typeof loadMappingFrom>>;",
  "  guard!: ScopeGuard;",
  "  adapter!: SlackAdapter | DiscordAdapter;",
  "  platform!: keyof typeof adapters;",
  "",
  "  constructor(",
  "    private source: string,",
  "    private platformOverride?: string,",
  "    private notionDb?: string,",
  "  ) {}",
  "",
  "  async reload(): Promise<void> {",
  "    let mapping = await loadMappingFrom(this.source);",
  "    if (this.notionDb) mapping = await loadWorkFromNotion(mapping, this.notionDb, clientFromEnv());",
  "    const platform = (this.platformOverride ?? mapping.platform) as keyof typeof adapters;",
  "    const Adapter = adapters[platform];",
  "    if (!Adapter) {",
  "      console.error(`unknown platform: ${platform}`);",
  "      process.exit(2);",
  "    }",
  "    this.mapping = mapping;",
  "    this.platform = platform;",
  "    this.guard = new ScopeGuard(mapping);",
  "    this.adapter = new Adapter(mapping, this.guard);",
  "  }",
  "}",
  "",
  "const { values } = parseArgs({",
  "  options: {",
  "    mapping: { type: \"string\" },",
  "    platform: { type: \"string\" },",
  '    "dry-run": { type: "boolean", default: false },',
  '    "collect-seconds": { type: "string" },',
  '    "notion-db": { type: "string" },',
  "  },",
  "});",
  "",
  "if (!values.mapping) {",
  '  console.error("usage: axiom-relay --mapping <file|url> [--platform slack|discord] [--dry-run]");',
  "  process.exit(2);",
  "}",
  "",
  "const runtime = new Runtime(values.mapping, values.platform, values[\"notion-db\"]);",
  "try {",
  "  await runtime.reload();",
  "} catch (err) {",
  "  if (err instanceof NotionError) {",
  "    console.error(err.message);",
  "    process.exit(2);",
  "  }",
  "  throw err;",
  "}",
  "",
  "const collect = Number(values[\"collect-seconds\"] ?? runtime.mapping.collectSeconds);",
  "",
  "if (values[\"dry-run\"]) {",
  "  runtime.adapter.describe();",
  "  process.stdout.write(",
  "    formatReport({",
  "      mapping: runtime.mapping,",
  "      guard: runtime.guard,",
  "      broadcastId: runtime.mapping.channels.find((c) => c.role === \"management\")!.id,",
  "      replyCount: 0,",
  "      collectSeconds: collect,",
  "    }),",
  "  );",
  "  if (values[\"notion-db\"]) {",
  "    const lines = await applyWrites(clientFromEnv(), plan(runtime.mapping), {}, {}, true);",
  "    for (const line of lines) console.log(line);",
  "  }",
  "  process.exit(0);",
  "}",
  "",
  "if (process.platform !== \"win32\") {",
  "  process.on(\"SIGHUP\", () => {",
  "    void runtime.reload();",
  "  });",
  "}",
  "",
  "runtime.adapter.run(collect);",
].join("\n");

const MAPPING = [
  "import { readFileSync } from \"node:fs\";",
  "",
  "export type Role = \"management\" | \"room\" | \"reports\";",
  "export type Direction = \"in\" | \"out\" | \"both\";",
  "export type Platform = \"slack\" | \"discord\";",
  "",
  "export type Channel = {",
  "  id: string;",
  "  name: string;",
  "  role: Role;",
  "  direction: Direction;",
  "};",
  "",
  "export type Work = {",
  "  id: string;",
  "  name: string;",
  "  room: string;",
  "  state: string;",
  "  anchor: string;",
  "  owner: string;",
  "  pageId?: string;",
  "};",
  "",
  "export type Mapping = {",
  "  workspace: string;",
  "  platform: Platform;",
  "  scope: string;",
  "  agent: string;",
  "  collectSeconds: number;",
  "  channels: Channel[];",
  "  work: Work[];",
  "};",
  "",
  "export class MappingError extends Error {}",
  "",
  "export async function readSource(source: string): Promise<string> {",
  '  if (source.startsWith("http://") || source.startsWith("https://")) {',
  '    const res = await fetch(source, { headers: { "User-Agent": "axiom-relay/0.3" } });',
  "    if (!res.ok) throw new MappingError(`mapping fetch ${res.status}`);",
  "    return await res.text();",
  "  }",
  "  return readFileSync(source, \"utf8\");",
  "}",
  "",
  "export async function loadMappingFrom(source: string): Promise<Mapping> {",
  "  return loadMapping(await readSource(source));",
  "}",
  "",
  "export function loadMapping(text: string): Mapping {",
  "  const { meta, body } = splitFrontMatter(text);",
  "  const { channels, work } = parseTables(body);",
  "  validate(meta, channels, work);",
  "  return {",
  "    workspace: meta.workspace,",
  "    platform: meta.platform as Platform,",
  "    scope: meta.scope,",
  "    agent: meta.agent,",
  "    collectSeconds: Number(meta.collect_seconds ?? 45),",
  "    channels,",
  "    work,",
  "  };",
  "}",
  "",
  "function splitFrontMatter(text: string): { meta: Record<string, string>; body: string } {",
  '  if (!text.startsWith("---")) throw new MappingError("mapping must start with YAML front matter");',
  "  const end = text.indexOf(\"\\n---\", 3);",
  "  if (end < 0) throw new MappingError(\"unterminated front matter\");",
  "  const raw = text.slice(3, end);",
  "  const body = text.slice(end + 4);",
  "  const meta: Record<string, string> = {};",
  "  for (const line of raw.split(\"\\n\")) {",
  "    if (!line.trim() || !line.includes(\":\")) continue;",
  "    const i = line.indexOf(\":\");",
  "    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();",
  "  }",
  "  return { meta, body };",
  "}",
  "",
  "function parseTables(body: string): { channels: Channel[]; work: Work[] } {",
  "  const channels: Channel[] = [];",
  "  const work: Work[] = [];",
  "  let header: string[] | null = null;",
  "  let rows: Record<string, string>[] = [];",
  "",
  "  const flush = () => {",
  "    if (!header) return;",
  "    const cols = new Set(header);",
  '    if (cols.has("role") && cols.has("direction")) {',
  "      for (const data of rows) {",
  "        channels.push({",
  "          id: data.id ?? \"\",",
  "          name: data.name ?? \"\",",
  "          role: (data.role ?? \"\") as Role,",
  "          direction: (data.direction ?? \"\") as Direction,",
  "        });",
  "      }",
  '    } else if (cols.has("room") && cols.has("state")) {',
  "      for (const data of rows) {",
  "        work.push({",
  "          id: data.id ?? \"\",",
  "          name: data.name ?? \"\",",
  "          room: data.room ?? \"\",",
  "          state: data.state ?? \"\",",
  "          anchor: data.anchor ?? \"\",",
  "          owner: data.owner ?? \"\",",
  "          pageId: data.page_id ?? \"\",",
  "        });",
  "      }",
  "    }",
  "    header = null;",
  "    rows = [];",
  "  };",
  "",
  "  for (const raw of body.split(\"\\n\")) {",
  "    const line = raw.trim();",
  '    if (!line.startsWith("|")) {',
  "      flush();",
  "      continue;",
  "    }",
  '    const cells = line.replace(/^\\||\\|$/g, "").split("|").map((c) => c.trim());',
  '    if (/^[-:\\s|]+$/.test(line)) continue;',
  "    if (!header) {",
  "      header = cells.map((c) => c.toLowerCase());",
  "      continue;",
  "    }",
  "    const data: Record<string, string> = {};",
  "    header.forEach((key, i) => {",
  "      data[key] = cells[i] ?? \"\";",
  "    });",
  "    rows.push(data);",
  "  }",
  "  flush();",
  "  return { channels, work };",
  "}",
  "",
  "export function plan(mapping: Mapping): { work: Work; action: \"post\" | \"gather\" | \"skip\" | \"gap\" }[] {",
  '  const rooms = new Set(mapping.channels.filter((c) => c.role === "room").map((c) => c.id));',
  "  return mapping.work.map((w) => {",
  "    if (!w.room || !rooms.has(w.room)) return { work: w, action: \"gap\" as const };",
  '    if (w.state === "closed") return { work: w, action: "skip" as const };',
  '    if (w.anchor) return { work: w, action: "gather" as const };',
  '    return { work: w, action: "post" as const };',
  "  });",
  "}",
  "",
  "export function replaceWork(mapping: Mapping, work: Work[]): Mapping {",
  "  return { ...mapping, work };",
  "}",
  "",
  "function validate(meta: Record<string, string>, channels: Channel[], work: Work[]) {",
  '  for (const key of ["workspace", "platform", "scope", "agent"]) {',
  "    if (!meta[key]) throw new MappingError(`missing ${key}`);",
  "  }",
  '  if (meta.platform !== "slack" && meta.platform !== "discord") {',
  "    throw new MappingError(`unknown platform ${meta.platform}`);",
  "  }",
  "  const ids = channels.map((c) => c.id);",
  "  if (new Set(ids).size !== ids.length) throw new MappingError(\"duplicate channel id\");",
  "  const hasMgmt = channels.some((c) => c.role === \"management\" && c.direction !== \"out\");",
  "  const hasReport = channels.some((c) => c.role === \"reports\" && c.direction !== \"in\");",
  "  if (!hasMgmt) throw new MappingError(\"need a management channel with direction in/both\");",
  "  if (!hasReport) throw new MappingError(\"need a reports channel with direction out/both\");",
  "  const workIds = work.map((w) => w.id);",
  "  if (new Set(workIds).size !== workIds.length) throw new MappingError(\"duplicate work id\");",
  "}",
].join("\n");

const SCOPE = [
  "import type { Mapping } from \"./mapping.ts\";",
  "",
  "export class ScopeError extends Error {}",
  "",
  "export class ScopeGuard {",
  "  readonly scope: string;",
  "  private ids: Set<string>;",
  "",
  "  constructor(mapping: Mapping) {",
  "    this.scope = mapping.scope;",
  "    this.ids = new Set(mapping.channels.map((c) => c.id));",
  "  }",
  "",
  "  allow(channelId: string): boolean {",
  "    return this.ids.has(channelId);",
  "  }",
  "",
  "  redact(channelId: string): string {",
  '    return this.allow(channelId) ? channelId : "<outside-scope>";',
  "  }",
  "",
  "  require(channelId: string, action: string): void {",
  "    if (!this.allow(channelId)) {",
  "      throw new ScopeError(`blocked ${action}: outside scope ${this.scope}`);",
  "    }",
  "  }",
  "",
  "  drop(_channelId: string, reason: string): void {",
  "    console.info(`dropped event source=<outside-scope> reason=${reason}`);",
  "  }",
  "}",
].join("\n");

const REPORT = [
  "import type { Mapping } from \"./mapping.ts\";",
  "import type { ScopeGuard } from \"./scope.ts\";",
  "import { plan } from \"./mapping.ts\";",
  "",
  "export type Crumb = {",
  "  authorId: string;",
  "  authorName: string;",
  "  claim: string;",
  "  permalink: string;",
  "};",
  "",
  "export function formatCrumb(crumb: Crumb): string | null {",
  "  if (!crumb.permalink || !crumb.claim) return null;",
  '  const who = crumb.authorName || `<unresolved:${crumb.authorId}>`;',
  "  return `  - ${who}: ${crumb.claim}  [${crumb.permalink}]`;",
  "}",
  "",
  "export function formatReport(opts: {",
  "  mapping: Mapping;",
  "  guard: ScopeGuard;",
  "  broadcastId: string;",
  "  replyCount: number;",
  "  collectSeconds: number;",
  "  trails?: Record<string, Crumb[]>;",
  "}): string {",
  "  if (opts.mapping.work.length) return formatWorkReport(opts.mapping, opts.guard, opts.trails ?? {});",
  "  opts.guard.require(opts.broadcastId, \"report\");",
  "  const rooms = opts.mapping.channels.filter((c) => c.role === \"room\");",
  "  const reports = opts.mapping.channels.filter((c) => c.role === \"reports\");",
  "  return [",
  "    `# report from ${opts.mapping.agent}`,",
  "    `scope: ${opts.mapping.scope}`,",
  "    `broadcast: ${opts.guard.redact(opts.broadcastId)}`,",
  "    `rooms: ${rooms.length}`,",
  "    `replies: ${opts.replyCount}`,",
  "    `window: ${opts.collectSeconds}s`,",
  "    `filed: ${reports.length} reports channel(s)`,",
  "    \"\",",
  "  ].join(\"\\n\");",
  "}",
  "",
  "function formatWorkReport(",
  "  mapping: Mapping,",
  "  guard: ScopeGuard,",
  "  trails: Record<string, Crumb[]>,",
  "): string {",
  "  const rows = plan(mapping);",
  "  const posts = rows.filter((r) => r.action === \"post\").length;",
  "  const gathers = rows.filter((r) => r.action === \"gather\").length;",
  "  const skips = rows.filter((r) => r.action === \"skip\").length;",
  "  const gaps = rows.filter((r) => r.action === \"gap\").length;",
  "  const lines = [",
  "    `# report from ${mapping.agent}`,",
  "    `scope: ${mapping.scope}`,",
  "    `work: ${rows.length}  post: ${posts}  gather: ${gathers}  skip: ${skips}  gaps: ${gaps}`,",
  "  ];",
  "  for (const { work: w, action } of rows) {",
  "    lines.push(\"\");",
  "    lines.push(`## ${w.id} — ${w.state || \"active\"}`);",
  "    if (action === \"gap\") {",
  "      lines.push(\"gaps: room not in map\");",
  "      continue;",
  "    }",
  "    lines.push(`room: ${guard.redact(w.room)}`);",
  "    if (w.owner) lines.push(`owner: ${w.owner}`);",
  "    if (action === \"post\") {",
  "      lines.push(\"anchor: (none — post, then gather next run)\");",
  "      lines.push(\"trail: (empty until the thread exists)\");",
  "    } else if (action === \"skip\") {",
  "      lines.push(\"skip: closed\");",
  "    } else {",
  "      lines.push(`anchor: ${w.anchor}`);",
  "      lines.push(\"action: gather\");",
  "      const crumbs = (trails[w.id] ?? []).map(formatCrumb).filter((c): c is string => c !== null);",
  "      if (crumbs.length) {",
  "        lines.push(\"trail:\");",
  "        lines.push(...crumbs);",
  "      } else {",
  "        lines.push(\"trail: silent (read this thread; do not open another)\");",
  "      }",
  "    }",
  "  }",
  "  lines.push(\"\");",
  "  return lines.join(\"\\n\");",
  "}",
].join("\n");

const SLACK = [
  "import type { Mapping } from \"./mapping.ts\";",
  "import type { ScopeGuard } from \"./scope.ts\";",
  "",
  "export class SlackAdapter {",
  "  constructor(",
  "    private mapping: Mapping,",
  "    private guard: ScopeGuard,",
  "  ) {}",
  "",
  "  describe(): void {",
  "    const m = this.mapping;",
  "    console.log(`axiom ${m.agent}  scope=${m.scope}  platform=slack`);",
  "    for (const ch of m.channels) {",
  "      console.log(`  ${ch.role.padEnd(12)} ${ch.direction.padEnd(4)}  ${ch.id}  ${ch.name}`);",
  "    }",
  "    console.log(`fan-out: ${m.channels.filter((c) => c.role === \"room\").length} room(s)`);",
  "  }",
  "",
  "  run(_collectSeconds: number): never {",
  "    for (const ch of this.mapping.channels) this.guard.require(ch.id, \"listen\");",
  '    throw new Error("live Slack requires SLACK_BOT_TOKEN");',
  "  }",
  "}",
].join("\n");

const DISCORD = [
  "import type { Mapping } from \"./mapping.ts\";",
  "import type { ScopeGuard } from \"./scope.ts\";",
  "",
  "export class DiscordAdapter {",
  "  constructor(",
  "    private mapping: Mapping,",
  "    private guard: ScopeGuard,",
  "  ) {}",
  "",
  "  describe(): void {",
  "    const m = this.mapping;",
  "    console.log(`axiom ${m.agent}  scope=${m.scope}  platform=discord`);",
  "    for (const ch of m.channels) {",
  "      console.log(`  ${ch.role.padEnd(12)} ${ch.direction.padEnd(4)}  ${ch.id}  ${ch.name}`);",
  "    }",
  "  }",
  "",
  "  run(_collectSeconds: number): never {",
  "    for (const ch of this.mapping.channels) this.guard.require(ch.id, \"listen\");",
  '    throw new Error("live Discord requires DISCORD_BOT_TOKEN");',
  "  }",
  "}",
].join("\n");

const NOTION = [
  "/** Notion is the live work ledger. Channels stay the markdown wall.",
  " *",
  " * Reads the Projects database and writes Broadcast TS, Broadcast Permalink,",
  " * and Last Status Update. Stdlib fetch. Token from NOTION_TOKEN.",
  " * Dry-run queries and prints writes; it does not PATCH.",
  " */",
  "import type { Mapping, Work } from \"./mapping.ts\";",
  "import { replaceWork } from \"./mapping.ts\";",
  "",
  "const API = \"https://api.notion.com/v1\";",
  "const NOTION_VERSION = \"2022-06-28\";",
  "const MAX_BLOCK = 2000;",
  "",
  "export const PROPS = {",
  "  name: \"Name\",",
  "  id: \"Scope key\",",
  "  room: \"Admin Channel\",",
  "  state: \"Status\",",
  "  anchor: \"Broadcast TS\",",
  "  owner: \"Owner\",",
  "  permalink: \"Broadcast Permalink\",",
  "  statusUpdate: \"Last Status Update\",",
  "} as const;",
  "",
  "const STATES: Record<string, string> = {",
  "  active: \"active\",",
  "  aligning: \"active\",",
  "  \"in progress\": \"active\",",
  "  \"in-progress\": \"active\",",
  "  blocked: \"blocked\",",
  "  closed: \"closed\",",
  "  done: \"closed\",",
  "  parked: \"closed\",",
  "};",
  "",
  "export type Transport = (method: string, url: string, headers: Record<string, string>, body?: string) => Promise<any>;",
  "",
  "export class NotionError extends Error {}",
  "",
  "async function defaultTransport(method: string, url: string, headers: Record<string, string>, body?: string) {",
  "  const res = await fetch(url, { method, headers, body });",
  "  if (!res.ok) throw new NotionError(`notion ${method} ${res.status}`);",
  "  return await res.json();",
  "}",
  "",
  "export class NotionClient {",
  "  constructor(",
  "    private token: string,",
  "    private transport: Transport = defaultTransport,",
  "  ) {",
  "    if (!token) throw new NotionError(\"NOTION_TOKEN is required\");",
  "  }",
  "",
  "  private headers() {",
  "    return {",
  "      Authorization: `Bearer ${this.token}`,",
  "      \"Notion-Version\": NOTION_VERSION,",
  "      \"Content-Type\": \"application/json\",",
  "      \"User-Agent\": \"axiom-relay/0.3\",",
  "    };",
  "  }",
  "",
  "  private call(method: string, path: string, payload?: unknown) {",
  "    return this.transport(method, API + path, this.headers(), payload ? JSON.stringify(payload) : undefined);",
  "  }",
  "",
  "  async queryWork(databaseId: string): Promise<Work[]> {",
  "    const rows: Work[] = [];",
  "    let cursor: string | undefined;",
  "    while (true) {",
  "      const payload: Record<string, unknown> = { page_size: 100 };",
  "      if (cursor) payload.start_cursor = cursor;",
  "      const data = await this.call(\"POST\", `/databases/${databaseId}/query`, payload);",
  "      for (const page of data.results ?? []) {",
  "        const w = workFromPage(page);",
  "        if (w) rows.push(w);",
  "      }",
  "      if (!data.has_more) break;",
  "      cursor = data.next_cursor;",
  "    }",
  "    return rows;",
  "  }",
  "",
  "  writeAnchor(pageId: string, ts: string, permalink: string) {",
  "    if (!ts) throw new NotionError(\"refusing empty Broadcast TS\");",
  "    return this.call(\"PATCH\", `/pages/${pageId}`, {",
  "      properties: {",
  "        [PROPS.anchor]: richText(ts),",
  "        [PROPS.permalink]: richText(permalink),",
  "      },",
  "    });",
  "  }",
  "",
  "  writeTrail(pageId: string, trail: string) {",
  "    return this.call(\"PATCH\", `/pages/${pageId}`, {",
  "      properties: { [PROPS.statusUpdate]: richText(clip(trail)) },",
  "    });",
  "  }",
  "}",
  "",
  "export function clip(text: string): string {",
  "  if (text.length <= MAX_BLOCK) return text;",
  "  const suffix = \"\\n(truncated)\";",
  "  return text.slice(0, MAX_BLOCK - suffix.length) + suffix;",
  "}",
  "",
  "function richText(content: string) {",
  "  return { rich_text: [{ type: \"text\", text: { content } }] };",
  "}",
  "",
  "function plain(prop: any): string {",
  "  if (!prop) return \"\";",
  "  if (prop.type === \"title\") return (prop.title ?? []).map((t: any) => t.plain_text ?? \"\").join(\"\");",
  "  if (prop.type === \"rich_text\") return (prop.rich_text ?? []).map((t: any) => t.plain_text ?? \"\").join(\"\");",
  "  if (prop.type === \"select\" || prop.type === \"status\") return prop[prop.type]?.name ?? \"\";",
  "  if (prop.type === \"url\") return prop.url ?? \"\";",
  "  if (prop.type === \"number\" && prop.number != null) return String(prop.number);",
  "  return \"\";",
  "}",
  "",
  "export function workFromPage(page: any): Work | null {",
  "  const props = page.properties ?? {};",
  "  const name = plain(props[PROPS.name]);",
  "  const key = plain(props[PROPS.id]) || name.toLowerCase().replace(/ /g, \"-\");",
  "  if (!key) return null;",
  "  const raw = plain(props[PROPS.state]).trim().toLowerCase();",
  "  return {",
  "    id: key,",
  "    name: name || key,",
  "    room: plain(props[PROPS.room]),",
  "    state: STATES[raw] ?? \"active\",",
  "    anchor: plain(props[PROPS.anchor]),",
  "    owner: plain(props[PROPS.owner]),",
  "    pageId: page.id ?? \"\",",
  "  };",
  "}",
  "",
  "export async function loadWorkFromNotion(mapping: Mapping, databaseId: string, client: NotionClient): Promise<Mapping> {",
  "  return replaceWork(mapping, await client.queryWork(databaseId));",
  "}",
  "",
  "export async function applyWrites(",
  "  client: NotionClient,",
  "  plan: { work: Work; action: string }[],",
  "  posts: Record<string, { ts: string; permalink: string }>,",
  "  trails: Record<string, string>,",
  "  dryRun: boolean,",
  "): Promise<string[]> {",
  "  const lines: string[] = [];",
  "  for (const { work: w, action } of plan) {",
  "    if (!w.pageId) {",
  "      lines.push(`notion  ${w.id.padEnd(16)}  skip  no page id`);",
  "      continue;",
  "    }",
  "    if (action === \"post\") {",
  "      const posted = posts[w.id];",
  "      if (!posted?.ts) {",
  "        lines.push(`notion  ${w.id.padEnd(16)}  POST    no ts — leave empty, retry next run`);",
  "        continue;",
  "      }",
  "      lines.push(`notion  ${w.id.padEnd(16)}  POST    write Broadcast TS + Permalink`);",
  "      if (!dryRun) await client.writeAnchor(w.pageId, posted.ts, posted.permalink);",
  "    } else if (action === \"gather\") {",
  "      lines.push(`notion  ${w.id.padEnd(16)}  GATHER  write Last Status Update`);",
  "      if (!dryRun) await client.writeTrail(w.pageId, trails[w.id] ?? \"silent\");",
  "    } else if (action === \"gap\") {",
  "      lines.push(`notion  ${w.id.padEnd(16)}  GAP     no write`);",
  "    } else {",
  "      lines.push(`notion  ${w.id.padEnd(16)}  SKIP    closed`);",
  "    }",
  "  }",
  "  return lines;",
  "}",
  "",
  "export function clientFromEnv(transport?: Transport): NotionClient {",
  "  return new NotionClient(process.env.NOTION_TOKEN ?? \"\", transport);",
  "}",
].join("\n");

const PKG = `{
  "name": "@axiom/scoped-relay",
  "version": "0.3.0",
  "type": "module",
  "license": "MIT",
  "bin": {
    "axiom-relay": "./relay.ts"
  },
  "scripts": {
    "dry-run": "npx tsx relay.ts --mapping ../../examples/mapping.md --dry-run"
  }
}
`;

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "types": ["node"]
  }
}
`;

export const NODE_FILES: RepoFile[] = [
  { path: "agent/node/relay.ts", language: "typescript", content: RELAY + "\n" },
  { path: "agent/node/mapping.ts", language: "typescript", content: MAPPING + "\n" },
  { path: "agent/node/scope.ts", language: "typescript", content: SCOPE + "\n" },
  { path: "agent/node/report.ts", language: "typescript", content: REPORT + "\n" },
  { path: "agent/node/slack.ts", language: "typescript", content: SLACK + "\n" },
  { path: "agent/node/discord.ts", language: "typescript", content: DISCORD + "\n" },
  { path: "agent/node/notion.ts", language: "typescript", content: NOTION + "\n" },
  { path: "agent/node/package.json", language: "json", content: PKG },
  { path: "agent/node/tsconfig.json", language: "json", content: TSCONFIG },
];
