import type { RepoFile } from "./types";

const INIT = '"""Axiom scoped relay — Python runtime."""\n';

const RELAY = [
  '"""Axiom scoped relay.',
  "",
  "Reads a channel-mapping markdown file, then:",
  "  1. Listens on management channels (direction: in)",
  "  2. Fans broadcasts into scoped rooms",
  "  3. Collects replies and posts a report",
  "",
  "Scope is a wall. Channels not listed in the mapping are invisible.",
  '"""',
  "",
  "from __future__ import annotations",
  "",
  "import argparse",
  "import logging",
  "import sys",
  "from pathlib import Path",
  "",
  "from .discord_adapter import DiscordAdapter",
  "from .mapping import load_mapping",
  "from .scope import ScopeGuard",
  "from .slack_adapter import SlackAdapter",
  "",
  "ADAPTERS = {",
  '    "slack": SlackAdapter,',
  '    "discord": DiscordAdapter,',
  "}",
  "",
  "",
  "def main(argv: list[str] | None = None) -> int:",
  '    parser = argparse.ArgumentParser(prog="axiom-relay")',
  '    parser.add_argument("--mapping", required=True)',
  '    parser.add_argument("--platform", choices=sorted(ADAPTERS))',
  '    parser.add_argument("--dry-run", action="store_true")',
  '    parser.add_argument("--collect-seconds", type=int, default=None)',
  "    args = parser.parse_args(argv)",
  "",
  "    text = Path(args.mapping).read_text(encoding=\"utf-8\")",
  "    mapping = load_mapping(text)",
  "    platform = args.platform or mapping.platform",
  "    if platform not in ADAPTERS:",
  '        logging.error("unknown platform: %s", platform)',
  "        return 2",
  "",
  "    guard = ScopeGuard(mapping)",
  "    adapter = ADAPTERS[platform](mapping, guard)",
  "    collect = args.collect_seconds or mapping.collect_seconds",
  "",
  "    if args.dry_run:",
  "        adapter.describe(sys.stdout)",
  "        return 0",
  "",
  "    adapter.run(collect_seconds=collect)",
  "    return 0",
  "",
  "",
  'if __name__ == "__main__":',
  "    raise SystemExit(main())",
].join("\n");

const MAPPING = [
  '"""Parse an Axiom mapping markdown file (front matter + table)."""',
  "",
  "from __future__ import annotations",
  "",
  "from dataclasses import dataclass",
  "",
  "ROLES = {\"management\", \"room\", \"reports\"}",
  "DIRECTIONS = {\"in\", \"out\", \"both\"}",
  "PLATFORMS = {\"slack\", \"discord\"}",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Channel:",
  "    id: str",
  "    name: str",
  "    role: str",
  "    direction: str",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Mapping:",
  "    workspace: str",
  "    platform: str",
  "    scope: str",
  "    agent: str",
  "    collect_seconds: int",
  "    channels: tuple[Channel, ...]",
  "",
  "    def ids(self) -> set[str]:",
  "        return {c.id for c in self.channels}",
  "",
  "    def by_role(self, role: str) -> tuple[Channel, ...]:",
  "        return tuple(c for c in self.channels if c.role == role)",
  "",
  "",
  "class MappingError(ValueError):",
  "    pass",
  "",
  "",
  "def load_mapping(text: str) -> Mapping:",
  "    meta, table = _split_front_matter(text)",
  "    channels = _parse_table(table)",
  "    _validate(meta, channels)",
  "    return Mapping(",
  '        workspace=meta["workspace"],',
  '        platform=meta["platform"],',
  '        scope=meta["scope"],',
  '        agent=meta["agent"],',
  '        collect_seconds=int(meta.get("collect_seconds", 45)),',
  "        channels=channels,",
  "    )",
  "",
  "",
  "def _split_front_matter(text: str) -> tuple[dict[str, str], str]:",
  '    if not text.startswith("---"):',
  '        raise MappingError("mapping must start with YAML front matter")',
  '    rest = text[3:]',
  '    end = rest.find("\\n---")',
  "    if end < 0:",
  '        raise MappingError("unterminated front matter")',
  "    raw, body = rest[:end], rest[end + 4 :]",
  "    meta: dict[str, str] = {}",
  "    for line in raw.splitlines():",
  '        if not line.strip() or ":" not in line:',
  "            continue",
  '        key, value = line.split(":", 1)',
  "        meta[key.strip()] = value.strip()",
  "    return meta, body",
  "",
  "",
  "def _parse_table(body: str) -> tuple[Channel, ...]:",
  "    rows: list[Channel] = []",
  "    header: list[str] | None = None",
  "    for raw in body.splitlines():",
  '        line = raw.strip()',
  '        if not line.startswith("|"):',
  "            continue",
  '        cells = [c.strip() for c in line.strip("|").split("|")]',
  '        if header is None:',
  "            header = [c.lower() for c in cells]",
  "            continue",
  '        if set("".join(cells)) <= set("-: "):',
  "            continue",
  "        data = dict(zip(header, cells))",
  "        rows.append(",
  "            Channel(",
  '                id=data["id"],',
  '                name=data.get("name", ""),',
  '                role=data["role"],',
  '                direction=data["direction"],',
  "            )",
  "        )",
  "    return tuple(rows)",
  "",
  "",
  "def _validate(meta: dict[str, str], channels: tuple[Channel, ...]) -> None:",
  '    for key in ("workspace", "platform", "scope", "agent"):',
  "        if not meta.get(key):",
  '            raise MappingError(f"missing {key}")',
  '    if meta["platform"] not in PLATFORMS:',
  '        raise MappingError(f"unknown platform {meta[\'platform\']!r}")',
  "    ids = [c.id for c in channels]",
  "    if len(ids) != len(set(ids)):",
  '        raise MappingError("duplicate channel id")',
  "    for ch in channels:",
  "        if ch.role not in ROLES:",
  '            raise MappingError(f"unknown role {ch.role!r}")',
  "        if ch.direction not in DIRECTIONS:",
  '            raise MappingError(f"unknown direction {ch.direction!r}")',
  '    if not any(c.role == "management" and c.direction in {"in", "both"} for c in channels):',
  '        raise MappingError("need a management channel with direction in/both")',
  '    if not any(c.role == "reports" and c.direction in {"out", "both"} for c in channels):',
  '        raise MappingError("need a reports channel with direction out/both")',
].join("\n");

const SCOPE = [
  '"""Scope is a wall. Adapters never see ids outside the mapping."""',
  "",
  "from __future__ import annotations",
  "",
  "from .mapping import Mapping",
  "",
  "",
  "class ScopeError(PermissionError):",
  "    pass",
  "",
  "",
  "class ScopeGuard:",
  "    def __init__(self, mapping: Mapping) -> None:",
  "        self.scope = mapping.scope",
  "        self._ids = mapping.ids()",
  "",
  "    def allow(self, channel_id: str) -> bool:",
  "        return channel_id in self._ids",
  "",
  "    def require(self, channel_id: str, action: str) -> None:",
  "        if not self.allow(channel_id):",
  "            raise ScopeError(",
  '                f"blocked {action} on {channel_id}: outside scope {self.scope!r}"',
  "            )",
].join("\n");

const SLACK = [
  '"""Slack adapter. Dry-run needs no SDK. Live import is deferred."""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import TextIO",
  "",
  "from .mapping import Mapping",
  "from .scope import ScopeGuard",
  "",
  "",
  "class SlackAdapter:",
  "    def __init__(self, mapping: Mapping, guard: ScopeGuard) -> None:",
  "        self.mapping = mapping",
  "        self.guard = guard",
  "",
  "    def describe(self, out: TextIO) -> None:",
  '        m = self.mapping',
  '        out.write(f"axiom {m.agent}  scope={m.scope}  platform=slack\\n")',
  "        for ch in m.channels:",
  '            out.write(f"  {ch.role:12} {ch.direction:4}  {ch.id}  {ch.name}\\n")',
  "        rooms = m.by_role(\"room\")",
  '        out.write(f"fan-out: {len(rooms)} room(s)  wall: {len(self.guard._ids)} id(s)\\n")',
  "",
  "    def run(self, collect_seconds: int) -> None:",
  "        for ch in self.mapping.channels:",
  '            self.guard.require(ch.id, "listen")',
  "        # Live path: slack_sdk WebClient + Socket Mode, filtered by guard.",
  '        raise SystemExit("live Slack requires SLACK_BOT_TOKEN and slack-sdk")',
].join("\n");

const DISCORD = [
  '"""Discord adapter. Same wall, different transport."""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import TextIO",
  "",
  "from .mapping import Mapping",
  "from .scope import ScopeGuard",
  "",
  "",
  "class DiscordAdapter:",
  "    def __init__(self, mapping: Mapping, guard: ScopeGuard) -> None:",
  "        self.mapping = mapping",
  "        self.guard = guard",
  "",
  "    def describe(self, out: TextIO) -> None:",
  "        m = self.mapping",
  '        out.write(f"axiom {m.agent}  scope={m.scope}  platform=discord\\n")',
  "        for ch in m.channels:",
  '            out.write(f"  {ch.role:12} {ch.direction:4}  {ch.id}  {ch.name}\\n")',
  '        out.write("unknown channel ids are dropped before on_message\\n")',
  "",
  "    def run(self, collect_seconds: int) -> None:",
  "        for ch in self.mapping.channels:",
  '            self.guard.require(ch.id, "listen")',
  '        raise SystemExit("live Discord requires DISCORD_BOT_TOKEN and discord.py")',
].join("\n");

const TEST_SCOPE = [
  "from mapping import load_mapping",
  "from scope import ScopeError, ScopeGuard",
  "",
  "SAMPLE = \"\"\"---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  '"""',
  "",
  "",
  "def test_unknown_channel_is_invisible():",
  "    mapping = load_mapping(SAMPLE)",
  "    guard = ScopeGuard(mapping)",
  "    assert guard.allow(\"C0OPS03\")",
  "    assert not guard.allow(\"C0SECRET\")",
  "    try:",
  '        guard.require("C0SECRET", "write")',
  "        raise AssertionError(\"wall failed\")",
  "    except ScopeError:",
  "        pass",
  "",
  "",
  'if __name__ == "__main__":',
  "    test_unknown_channel_is_invisible()",
  '    print("ok")',
].join("\n");

const REQUIREMENTS = [
  "# stdlib is enough for dry-run and mapping tests.",
  "# Live adapters (optional):",
  "# slack-sdk>=3.33",
  "# discord.py>=2.4",
  "",
].join("\n");

export const PYTHON_FILES: RepoFile[] = [
  { path: "agent/python/__init__.py", language: "python", content: INIT },
  { path: "agent/python/relay.py", language: "python", content: RELAY + "\n" },
  { path: "agent/python/mapping.py", language: "python", content: MAPPING + "\n" },
  { path: "agent/python/scope.py", language: "python", content: SCOPE + "\n" },
  { path: "agent/python/slack_adapter.py", language: "python", content: SLACK + "\n" },
  { path: "agent/python/discord_adapter.py", language: "python", content: DISCORD + "\n" },
  { path: "agent/python/test_scope.py", language: "python", content: TEST_SCOPE + "\n" },
  { path: "agent/python/requirements.txt", language: "text", content: REQUIREMENTS },
];
