import type { RepoFile } from "./types";

const INIT = '"""Axiom scoped relay — Python runtime."""\n';

const RELAY = [
  '"""Axiom scoped relay.',
  "",
  "Reads a channel-mapping markdown file (path or https URL), then:",
  "  1. Listens on management channels (direction: in)",
  "  2. Fans broadcasts into scoped rooms",
  "  3. Collects replies and posts a report",
  "",
  "Scope is a wall. Channels not listed in the mapping are invisible.",
  "SIGHUP reloads the map without a restart.",
  '"""',
  "",
  "from __future__ import annotations",
  "",
  "import argparse",
  "import logging",
  "import signal",
  "import sys",
  "from pathlib import Path",
  "",
  "if __package__ is None:",
  "    sys.path.insert(0, str(Path(__file__).resolve().parent))",
  "",
  "from discord_adapter import DiscordAdapter",
  "from mapping import load_mapping_from",
  "from notion import NotionError, apply_writes, client_from_env, load_work_from_notion",
  "from report import format_report",
  "from scope import ScopeGuard",
  "from slack_adapter import SlackAdapter",
  "",
  "ADAPTERS = {",
  '    "slack": SlackAdapter,',
  '    "discord": DiscordAdapter,',
  "}",
  "",
  "",
  "class Runtime:",
  "    def __init__(self, source: str, platform: str | None, notion_db: str | None = None) -> None:",
  "        self.source = source",
  "        self.platform_override = platform",
  "        self.notion_db = notion_db",
  "        self.reload()",
  "",
  "    def reload(self) -> None:",
  "        mapping = load_mapping_from(self.source)",
  "        if self.notion_db:",
  "            mapping = load_work_from_notion(mapping, self.notion_db, client_from_env())",
  "        platform = self.platform_override or mapping.platform",
  "        if platform not in ADAPTERS:",
  '            raise SystemExit(f"unknown platform: {platform}")',
  "        self.mapping = mapping",
  "        self.platform = platform",
  "        self.guard = ScopeGuard(mapping)",
  "        self.adapter = ADAPTERS[platform](mapping, self.guard)",
  '        logging.info("loaded scope=%s ids=%d work=%d", mapping.scope, len(mapping.ids()), len(mapping.work))',
  "",
  "",
  "def main(argv: list[str] | None = None) -> int:",
  '    parser = argparse.ArgumentParser(prog="axiom-relay")',
  '    parser.add_argument("--mapping", required=True, help="path or https URL")',
  '    parser.add_argument("--platform", choices=sorted(ADAPTERS))',
  '    parser.add_argument("--dry-run", action="store_true")',
  '    parser.add_argument("--collect-seconds", type=int, default=None)',
  '    parser.add_argument("--notion-db", default=None, help="Notion Projects database id")',
  "    args = parser.parse_args(argv)",
  "",
  "    try:",
  "        runtime = Runtime(args.mapping, args.platform, args.notion_db)",
  "    except NotionError as err:",
  "        raise SystemExit(str(err)) from err",
  "    collect = args.collect_seconds or runtime.mapping.collect_seconds",
  "",
  "    if args.dry_run:",
  "        runtime.adapter.describe(sys.stdout)",
  "        sys.stdout.write(format_report(",
  "            mapping=runtime.mapping,",
  "            guard=runtime.guard,",
  '            broadcast_id=runtime.mapping.by_role("management")[0].id,',
  "            reply_count=0,",
  "            collect_seconds=collect,",
  "        ))",
  "        if args.notion_db:",
  "            for line in apply_writes(client_from_env(), runtime.mapping.plan(), {}, {}, dry_run=True):",
  "                sys.stdout.write(line + \"\\n\")",
  "        return 0",
  "",
  "    if hasattr(signal, \"SIGHUP\"):",
  "        signal.signal(signal.SIGHUP, lambda *_: runtime.reload())",
  "",
  "    runtime.adapter.run(collect_seconds=collect)",
  "    return 0",
  "",
  "",
  'if __name__ == "__main__":',
  "    raise SystemExit(main())",
].join("\n");

const MAPPING = [
  '"""Parse an Axiom mapping markdown file (front matter + table)."""',
  "",
  "from __future__ import annotations",
  "",
  "from dataclasses import dataclass",
  "from pathlib import Path",
  "from urllib.request import Request, urlopen",
  "",
  "ROLES = {\"management\", \"room\", \"reports\"}",
  "DIRECTIONS = {\"in\", \"out\", \"both\"}",
  "PLATFORMS = {\"slack\", \"discord\"}",
  "WORK_STATES = {\"active\", \"blocked\", \"closed\"}",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Channel:",
  "    id: str",
  "    name: str",
  "    role: str",
  "    direction: str",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Work:",
  "    id: str",
  "    name: str",
  "    room: str",
  "    state: str",
  "    anchor: str",
  "    owner: str",
  "    page_id: str = \"\"",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Mapping:",
  "    workspace: str",
  "    platform: str",
  "    scope: str",
  "    agent: str",
  "    collect_seconds: int",
  "    channels: tuple[Channel, ...]",
  "    work: tuple[Work, ...]",
  "",
  "    def ids(self) -> set[str]:",
  "        return {c.id for c in self.channels}",
  "",
  "    def by_role(self, role: str) -> tuple[Channel, ...]:",
  "        return tuple(c for c in self.channels if c.role == role)",
  "",
  "    def room_ids(self) -> set[str]:",
  "        return {c.id for c in self.channels if c.role == \"room\"}",
  "",
  "    def plan(self) -> tuple[tuple[Work, str], ...]:",
  '        """Each work row is a broadcast. action is post, gather, skip, or gap."""',
  "        rooms = self.room_ids()",
  "        out: list[tuple[Work, str]] = []",
  "        for w in self.work:",
  "            if not w.room or w.room not in rooms:",
  '                out.append((w, "gap"))',
  "            elif w.state == \"closed\":",
  '                out.append((w, "skip"))',
  "            elif w.anchor:",
  '                out.append((w, "gather"))',
  "            else:",
  '                out.append((w, "post"))',
  "        return tuple(out)",
  "",
  "    def replace_work(self, work: tuple[Work, ...]) -> Mapping:",
  "        return Mapping(",
  "            workspace=self.workspace,",
  "            platform=self.platform,",
  "            scope=self.scope,",
  "            agent=self.agent,",
  "            collect_seconds=self.collect_seconds,",
  "            channels=self.channels,",
  "            work=work,",
  "        )",
  "",
  "",
  "class MappingError(ValueError):",
  "    pass",
  "",
  "",
  "def read_source(source: str) -> str:",
  '    if source.startswith(("http://", "https://")):',
  '        req = Request(source, headers={"User-Agent": "axiom-relay/0.3"})',
  "        with urlopen(req, timeout=15) as resp:",
  "            return resp.read().decode(\"utf-8\")",
  "    return Path(source).read_text(encoding=\"utf-8\")",
  "",
  "",
  "def load_mapping_from(source: str) -> Mapping:",
  "    return load_mapping(read_source(source))",
  "",
  "",
  "def load_mapping(text: str) -> Mapping:",
  "    meta, table = _split_front_matter(text)",
  "    channels, work = _parse_tables(table)",
  "    _validate(meta, channels, work)",
  "    return Mapping(",
  '        workspace=meta["workspace"],',
  '        platform=meta["platform"],',
  '        scope=meta["scope"],',
  '        agent=meta["agent"],',
  '        collect_seconds=int(meta.get("collect_seconds", 45)),',
  "        channels=channels,",
  "        work=work,",
  "    )",
  "",
  "",
  "def _split_front_matter(text: str) -> tuple[dict[str, str], str]:",
  '    if not text.startswith("---"):',
  '        raise MappingError("mapping must start with YAML front matter")',
  '    rest = text[3:]',
  '    end = rest.find("\\n---")',
  "    if end < 0:",
  '        raise MappingError("unterminated front matter")',
  "    raw, body = rest[:end], rest[end + 4 :]",
  "    meta: dict[str, str] = {}",
  "    for line in raw.splitlines():",
  '        if not line.strip() or ":" not in line:',
  "            continue",
  '        key, value = line.split(":", 1)',
  "        meta[key.strip()] = value.strip()",
  "    return meta, body",
  "",
  "",
  "def _parse_tables(body: str) -> tuple[tuple[Channel, ...], tuple[Work, ...]]:",
  "    channels: list[Channel] = []",
  "    work: list[Work] = []",
  "    header: list[str] | None = None",
  "    rows: list[dict[str, str]] = []",
  "",
  "    def flush() -> None:",
  "        nonlocal header, rows",
  "        if header:",
  "            cols = set(header)",
  '            if "role" in cols and "direction" in cols:',
  "                for data in rows:",
  "                    channels.append(",
  "                        Channel(",
  '                            id=data.get("id", ""),',
  '                            name=data.get("name", ""),',
  '                            role=data.get("role", ""),',
  '                            direction=data.get("direction", ""),',
  "                        )",
  "                    )",
  '            elif "room" in cols and "state" in cols:',
  "                for data in rows:",
  "                    work.append(",
  "                        Work(",
  '                            id=data.get("id", ""),',
  '                            name=data.get("name", ""),',
  '                            room=data.get("room", ""),',
  '                            state=data.get("state", ""),',
  '                            anchor=data.get("anchor", ""),',
  '                            owner=data.get("owner", ""),',
  '                            page_id=data.get("page_id", ""),',
  "                        )",
  "                    )",
  "        header = None",
  "        rows = []",
  "",
  "    for raw in body.splitlines():",
  "        line = raw.strip()",
  '        if not line.startswith("|"):',
  "            flush()",
  "            continue",
  '        cells = [c.strip() for c in line.strip("|").split("|")]',
  '        if set("".join(cells)) <= set("-: "):',
  "            continue",
  "        if header is None:",
  "            header = [c.lower() for c in cells]",
  "            continue",
  "        rows.append(dict(zip(header, cells)))",
  "    flush()",
  "    return tuple(channels), tuple(work)",
  "",
  "",
  "def _validate(",
  "    meta: dict[str, str],",
  "    channels: tuple[Channel, ...],",
  "    work: tuple[Work, ...],",
  ") -> None:",
  '    for key in ("workspace", "platform", "scope", "agent"):',
  "        if not meta.get(key):",
  '            raise MappingError(f"missing {key}")',
  '    if meta["platform"] not in PLATFORMS:',
  '        raise MappingError(f"unknown platform {meta[\'platform\']!r}")',
  "    ids = [c.id for c in channels]",
  "    if len(ids) != len(set(ids)):",
  '        raise MappingError("duplicate channel id")',
  "    for ch in channels:",
  "        if ch.role not in ROLES:",
  '            raise MappingError(f"unknown role {ch.role!r}")',
  "        if ch.direction not in DIRECTIONS:",
  '            raise MappingError(f"unknown direction {ch.direction!r}")',
  '    if not any(c.role == "management" and c.direction in {"in", "both"} for c in channels):',
  '        raise MappingError("need a management channel with direction in/both")',
  '    if not any(c.role == "reports" and c.direction in {"out", "both"} for c in channels):',
  '        raise MappingError("need a reports channel with direction out/both")',
  "    work_ids = [w.id for w in work]",
  "    if len(work_ids) != len(set(work_ids)):",
  '        raise MappingError("duplicate work id")',
  "    for w in work:",
  "        if w.state and w.state not in WORK_STATES:",
  '            raise MappingError(f"unknown work state {w.state!r}")',
].join("\n");

const SCOPE = [
  '"""Scope is a wall. Adapters never see ids outside the mapping."""',
  "",
  "from __future__ import annotations",
  "",
  "import logging",
  "",
  "from mapping import Mapping",
  "",
  "",
  "class ScopeError(PermissionError):",
  "    pass",
  "",
  "",
  "class ScopeGuard:",
  "    def __init__(self, mapping: Mapping) -> None:",
  "        self.scope = mapping.scope",
  "        self._ids = mapping.ids()",
  "",
  "    def allow(self, channel_id: str) -> bool:",
  "        return channel_id in self._ids",
  "",
  "    def redact(self, channel_id: str) -> str:",
  '        return channel_id if self.allow(channel_id) else "<outside-scope>"',
  "",
  "    def require(self, channel_id: str, action: str) -> None:",
  "        if not self.allow(channel_id):",
  "            raise ScopeError(",
  '                f"blocked {action}: outside scope {self.scope!r}"',
  "            )",
  "",
  "    def drop(self, channel_id: str, reason: str) -> None:",
  "        # The raw id never leaves this function.",
  '        logging.info("dropped event source=<outside-scope> reason=%s", reason)',
].join("\n");

const REPORT = [
  '"""Broadcast plan and breadcrumb trail. A crumb is a cited reply, or it is omitted."""',
  "",
  "from __future__ import annotations",
  "",
  "from dataclasses import dataclass",
  "",
  "from mapping import Mapping",
  "from scope import ScopeGuard",
  "",
  "",
  "@dataclass(frozen=True)",
  "class Crumb:",
  "    author_id: str",
  "    author_name: str",
  "    claim: str",
  "    permalink: str",
  "",
  "",
  "def format_crumb(crumb: Crumb) -> str | None:",
  "    if not crumb.permalink or not crumb.claim:",
  "        return None",
  '    who = crumb.author_name or ("<unresolved:" + crumb.author_id + ">")',
  '    return f"  - {who}: {crumb.claim}  [{crumb.permalink}]"',
  "",
  "",
  "def format_report(",
  "    *,",
  "    mapping: Mapping,",
  "    guard: ScopeGuard,",
  "    broadcast_id: str,",
  "    reply_count: int,",
  "    collect_seconds: int,",
  "    trails: dict[str, tuple[Crumb, ...]] | None = None,",
  ") -> str:",
  "    if mapping.work:",
  "        return _format_work_report(mapping, guard, trails or {})",
  '    guard.require(broadcast_id, "report")',
  "    rooms = mapping.by_role(\"room\")",
  "    reports = mapping.by_role(\"reports\")",
  "    lines = [",
  '        f"# report from {mapping.agent}",',
  '        f"scope: {mapping.scope}",',
  '        f"broadcast: {guard.redact(broadcast_id)}",',
  '        f"rooms: {len(rooms)}",',
  '        f"replies: {reply_count}",',
  '        f"window: {collect_seconds}s",',
  '        f"filed: {len(reports)} reports channel(s)",',
  "    ]",
  '    return "\\n".join(lines) + "\\n"',
  "",
  "",
  "def _format_work_report(",
  "    mapping: Mapping,",
  "    guard: ScopeGuard,",
  "    trails: dict[str, tuple[Crumb, ...]],",
  ") -> str:",
  "    plan = mapping.plan()",
  "    posts = sum(1 for _, a in plan if a == \"post\")",
  "    gathers = sum(1 for _, a in plan if a == \"gather\")",
  "    skips = sum(1 for _, a in plan if a == \"skip\")",
  "    gaps = sum(1 for _, a in plan if a == \"gap\")",
  "    lines = [",
  '        f"# report from {mapping.agent}",',
  '        f"scope: {mapping.scope}",',
  '        f"work: {len(plan)}  post: {posts}  gather: {gathers}  skip: {skips}  gaps: {gaps}",',
  "    ]",
  "    for w, action in plan:",
  '        lines.append("")',
  '        lines.append("## " + w.id + " — " + (w.state or "active"))',
  "        if action == \"gap\":",
  '            lines.append("gaps: room not in map")',
  "            continue",
  '        lines.append(f"room: {guard.redact(w.room)}")',
  "        if w.owner:",
  '            lines.append(f"owner: {w.owner}")',
  "        if action == \"post\":",
  '            lines.append("anchor: (none — post, then gather next run)")',
  '            lines.append("trail: (empty until the thread exists)")',
  "        elif action == \"skip\":",
  '            lines.append("skip: closed")',
  "        else:",
  '            lines.append(f"anchor: {w.anchor}")',
  '            lines.append("action: gather")',
  "            crumbs = [c for c in (format_crumb(x) for x in trails.get(w.id, ())) if c]",
  "            if crumbs:",
  '                lines.append("trail:")',
  "                lines.extend(crumbs)",
  "            else:",
  '                lines.append("trail: silent (read this thread; do not open another)")',
  '    return "\\n".join(lines) + "\\n"',
].join("\n");

const SLACK = [
  '"""Slack adapter. Dry-run needs no SDK. Live import is deferred."""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import TextIO",
  "",
  "from mapping import Mapping",
  "from scope import ScopeGuard",
  "",
  "",
  "class SlackAdapter:",
  "    def __init__(self, mapping: Mapping, guard: ScopeGuard) -> None:",
  "        self.mapping = mapping",
  "        self.guard = guard",
  "",
  "    def describe(self, out: TextIO) -> None:",
  '        m = self.mapping',
  '        out.write(f"axiom {m.agent}  scope={m.scope}  platform=slack\\n")',
  "        for ch in m.channels:",
  '            out.write(f"  {ch.role:12} {ch.direction:4}  {ch.id}  {ch.name}\\n")',
  "        rooms = m.by_role(\"room\")",
  '        out.write(f"fan-out: {len(rooms)} room(s)  wall: {len(self.guard._ids)} id(s)\\n")',
  "",
  "    def run(self, collect_seconds: int) -> None:",
  "        for ch in self.mapping.channels:",
  '            self.guard.require(ch.id, "listen")',
  "        # Live path: slack_sdk WebClient + Socket Mode, filtered by guard.",
  '        raise SystemExit("live Slack requires SLACK_BOT_TOKEN and slack-sdk")',
].join("\n");

const DISCORD = [
  '"""Discord adapter. Same wall, different transport."""',
  "",
  "from __future__ import annotations",
  "",
  "from typing import TextIO",
  "",
  "from mapping import Mapping",
  "from scope import ScopeGuard",
  "",
  "",
  "class DiscordAdapter:",
  "    def __init__(self, mapping: Mapping, guard: ScopeGuard) -> None:",
  "        self.mapping = mapping",
  "        self.guard = guard",
  "",
  "    def describe(self, out: TextIO) -> None:",
  "        m = self.mapping",
  '        out.write(f"axiom {m.agent}  scope={m.scope}  platform=discord\\n")',
  "        for ch in m.channels:",
  '            out.write(f"  {ch.role:12} {ch.direction:4}  {ch.id}  {ch.name}\\n")',
  '        out.write("unknown channel ids are dropped before on_message\\n")',
  "",
  "    def run(self, collect_seconds: int) -> None:",
  "        for ch in self.mapping.channels:",
  '            self.guard.require(ch.id, "listen")',
  '        raise SystemExit("live Discord requires DISCORD_BOT_TOKEN and discord.py")',
].join("\n");

const TEST_SCOPE = [
  "from mapping import load_mapping",
  "from scope import ScopeError, ScopeGuard",
  "",
  "SAMPLE = \"\"\"---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  '"""',
  "",
  "",
  "def test_unknown_channel_is_invisible():",
  "    mapping = load_mapping(SAMPLE)",
  "    guard = ScopeGuard(mapping)",
  "    assert guard.allow(\"C0OPS03\")",
  "    assert not guard.allow(\"C0SECRET\")",
  "    try:",
  '        guard.require("C0SECRET", "write")',
  "        raise AssertionError(\"wall failed\")",
  "    except ScopeError as err:",
  "        assert \"C0SECRET\" not in str(err)",
  "",
  "",
  "def test_redact_does_not_echo_unknown_id():",
  "    guard = ScopeGuard(load_mapping(SAMPLE))",
  '    assert guard.redact("C0OPS03") == "C0OPS03"',
  '    assert guard.redact("C0SECRET") == "<outside-scope>"',
  "",
  "",
  'if __name__ == "__main__":',
  "    test_unknown_channel_is_invisible()",
  "    test_redact_does_not_echo_unknown_id()",
  '    print("ok")',
].join("\n");

const TEST_MAPPING = [
  "from mapping import MappingError, load_mapping",
  "",
  "V02 = \"\"\"---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  '"""',
  "",
  "WORK = \"\"\"---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  "| C0LAUNCH | #launch | room | both |",
  "",
  "| id | name | room | state | anchor | owner |",
  "|----|------|------|-------|--------|-------|",
  "| north-star | North Star launch | C0OPS03 | active | | U08AAAA |",
  "| beta-waitlist | Beta waitlist | C0LAUNCH | active | 1000000000.000001 | U06BBBB |",
  "| no-room | Unmapped work | C0GHOST | active | | U06CCCC |",
  '"""',
  "",
  "",
  "def test_missing_management_is_an_error():",
  "    text = \"\"\"---",
  "workspace: x",
  "platform: slack",
  "scope: team.x",
  "agent: r",
  "---",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C1 | #r | reports | out |",
  '"""',
  "    try:",
  "        load_mapping(text)",
  "        raise AssertionError(\"accepted a map with no management channel\")",
  "    except MappingError:",
  "        pass",
  "",
  "",
  "def test_v02_map_has_no_work():",
  "    m = load_mapping(V02)",
  "    assert m.work == ()",
  "    assert m.plan() == ()",
  "",
  "",
  "def test_work_plan_post_gather_gap():",
  "    m = load_mapping(WORK)",
  "    actions = {w.id: a for w, a in m.plan()}",
  '    assert actions["north-star"] == "post"',
  '    assert actions["beta-waitlist"] == "gather"',
  '    assert actions["no-room"] == "gap"',
  "",
  "",
  "def test_duplicate_work_id_is_an_error():",
  "    text = WORK.replace(\"| no-room |\", \"| north-star |\", 1)",
  "    try:",
  "        load_mapping(text)",
  "        raise AssertionError(\"accepted duplicate work id\")",
  "    except MappingError as err:",
  '        assert "duplicate work id" in str(err)',
  "",
  "",
  'if __name__ == "__main__":',
  "    test_missing_management_is_an_error()",
  "    test_v02_map_has_no_work()",
  "    test_work_plan_post_gather_gap()",
  "    test_duplicate_work_id_is_an_error()",
  '    print("ok")',
].join("\n");

const TEST_REPORT = [
  "from report import Crumb, format_crumb",
  "",
  "",
  "def test_crumb_without_permalink_is_dropped():",
  "    c = Crumb(author_id=\"U1\", author_name=\"Ada\", claim=\"shipped\", permalink=\"\")",
  "    assert format_crumb(c) is None",
  "",
  "",
  "def test_unresolved_author_is_not_named():",
  "    c = Crumb(",
  "        author_id=\"U0NONE01\",",
  '        author_name="",',
  '        claim="thank you",',
  '        permalink="https://example.slack.com/archives/C0OPS03/p1",',
  "    )",
  "    line = format_crumb(c)",
  '    assert line is not None',
  '    assert "Ada" not in line',
  '    assert "<unresolved:U0NONE01>" in line',
  '    assert "https://example.slack.com/archives/C0OPS03/p1" in line',
  "",
  "",
  'if __name__ == "__main__":',
  "    test_crumb_without_permalink_is_dropped()",
  "    test_unresolved_author_is_not_named()",
  '    print("ok")',
].join("\n");

const NOTION = [
  '"""Notion is the live work ledger. Channels stay the markdown wall.',
  "",
  "The agent reads the Projects database and writes back:",
  "  - Broadcast TS + Broadcast Permalink after a post",
  "  - Last Status Update after a gather (the breadcrumb trail)",
  "",
  "Stdlib HTTP only. Token from NOTION_TOKEN. Dry-run queries and prints",
  "writes; it does not PATCH.",
  '"""',
  "",
  "from __future__ import annotations",
  "",
  "import json",
  "import os",
  "from typing import Any, Callable",
  "from urllib.error import HTTPError, URLError",
  "from urllib.request import Request, urlopen",
  "",
  "from mapping import Mapping, Work",
  "",
  "API = \"https://api.notion.com/v1\"",
  "NOTION_VERSION = \"2022-06-28\"",
  "MAX_BLOCK = 2000",
  "",
  "PROPS = {",
  '    "name": "Name",',
  '    "id": "Scope key",',
  '    "room": "Admin Channel",',
  '    "state": "Status",',
  '    "anchor": "Broadcast TS",',
  '    "owner": "Owner",',
  '    "permalink": "Broadcast Permalink",',
  '    "status_update": "Last Status Update",',
  "}",
  "",
  "STATES = {",
  '    "active": "active",',
  '    "aligning": "active",',
  '    "in progress": "active",',
  '    "in-progress": "active",',
  '    "blocked": "blocked",',
  '    "closed": "closed",',
  '    "done": "closed",',
  '    "parked": "closed",',
  "}",
  "",
  "Transport = Callable[[str, str, dict[str, str], bytes | None], dict[str, Any]]",
  "",
  "",
  "class NotionError(RuntimeError):",
  "    pass",
  "",
  "",
  "def default_transport(method: str, url: str, headers: dict[str, str], body: bytes | None) -> dict[str, Any]:",
  "    req = Request(url, data=body, method=method, headers=headers)",
  "    try:",
  "        with urlopen(req, timeout=20) as resp:",
  "            return json.loads(resp.read().decode(\"utf-8\"))",
  "    except HTTPError as err:",
  "        raise NotionError(f\"notion {method} {err.code}\") from err",
  "    except URLError as err:",
  "        raise NotionError(\"notion unreachable\") from err",
  "",
  "",
  "class NotionClient:",
  "    def __init__(self, token: str, transport: Transport | None = None) -> None:",
  "        if not token:",
  '            raise NotionError("NOTION_TOKEN is required")',
  "        self.token = token",
  "        self.transport = transport or default_transport",
  "",
  "    def _headers(self) -> dict[str, str]:",
  "        return {",
  '            "Authorization": "Bearer " + self.token,',
  '            "Notion-Version": NOTION_VERSION,',
  '            "Content-Type": "application/json",',
  '            "User-Agent": "axiom-relay/0.3",',
  "        }",
  "",
  "    def _call(self, method: str, path: str, payload: dict[str, Any] | None = None) -> dict[str, Any]:",
  "        body = json.dumps(payload).encode(\"utf-8\") if payload is not None else None",
  "        return self.transport(method, API + path, self._headers(), body)",
  "",
  "    def query_work(self, database_id: str) -> tuple[Work, ...]:",
  "        rows: list[Work] = []",
  "        cursor: str | None = None",
  "        while True:",
  "            payload: dict[str, Any] = {\"page_size\": 100}",
  "            if cursor:",
  '                payload["start_cursor"] = cursor',
  '            data = self._call("POST", "/databases/" + database_id + "/query", payload)',
  "            for page in data.get(\"results\", []):",
  "                w = work_from_page(page)",
  "                if w:",
  "                    rows.append(w)",
  "            if not data.get(\"has_more\"):",
  "                break",
  "            cursor = data.get(\"next_cursor\")",
  "        return tuple(rows)",
  "",
  "    def write_anchor(self, page_id: str, ts: str, permalink: str) -> None:",
  "        if not ts:",
  '            raise NotionError("refusing empty Broadcast TS")',
  "        self._call(",
  '            "PATCH",',
  '            "/pages/" + page_id,',
  "            {",
  '                "properties": {',
  '                    PROPS["anchor"]: rich_text(ts),',
  '                    PROPS["permalink"]: rich_text(permalink),',
  "                }",
  "            },",
  "        )",
  "",
  "    def write_trail(self, page_id: str, trail: str) -> None:",
  "        self._call(",
  '            "PATCH",',
  '            "/pages/" + page_id,',
  '            {"properties": {PROPS["status_update"]: rich_text(clip(trail))}},',
  "        )",
  "",
  "",
  "def clip(text: str) -> str:",
  "    if len(text) <= MAX_BLOCK:",
  "        return text",
  '    suffix = "\\n(truncated)"',
  "    return text[: MAX_BLOCK - len(suffix)] + suffix",
  "",
  "",
  "def rich_text(content: str) -> dict[str, Any]:",
  '    return {"rich_text": [{"type": "text", "text": {"content": content}}]}',
  "",
  "",
  "def _plain(prop: dict[str, Any] | None) -> str:",
  "    if not prop:",
  '        return ""',
  '    kind = prop.get("type")',
  "    if kind == \"title\":",
  '        return "".join(t.get("plain_text", "") for t in prop.get("title", []))',
  "    if kind == \"rich_text\":",
  '        return "".join(t.get("plain_text", "") for t in prop.get("rich_text", []))',
  "    if kind in {\"select\", \"status\"}:",
  "        node = prop.get(kind) or {}",
  '        return str(node.get("name") or "")',
  "    if kind == \"url\":",
  '        return str(prop.get("url") or "")',
  "    if kind == \"number\" and prop.get(\"number\") is not None:",
  '        return str(prop["number"])',
  '    return ""',
  "",
  "",
  "def normalize_state(raw: str) -> str:",
  '    return STATES.get(raw.strip().lower(), "active" if raw else "active")',
  "",
  "",
  "def work_from_page(page: dict[str, Any]) -> Work | None:",
  '    props = page.get("properties") or {}',
  "    name = _plain(props.get(PROPS[\"name\"]))",
  "    key = _plain(props.get(PROPS[\"id\"])) or name.lower().replace(\" \", \"-\")",
  "    if not key:",
  "        return None",
  "    return Work(",
  "        id=key,",
  "        name=name or key,",
  '        room=_plain(props.get(PROPS["room"])),',
  '        state=normalize_state(_plain(props.get(PROPS["state"]))),',
  '        anchor=_plain(props.get(PROPS["anchor"])),',
  '        owner=_plain(props.get(PROPS["owner"])),',
  '        page_id=str(page.get("id") or ""),',
  "    )",
  "",
  "",
  "def load_work_from_notion(mapping: Mapping, database_id: str, client: NotionClient) -> Mapping:",
  "    return mapping.replace_work(client.query_work(database_id))",
  "",
  "",
  "def apply_writes(",
  "    client: NotionClient,",
  "    plan: tuple[tuple[Work, str], ...],",
  "    posts: dict[str, tuple[str, str]],",
  "    trails: dict[str, str],",
  "    *,",
  "    dry_run: bool,",
  ") -> list[str]:",
  '    """Write anchors and trails back to Notion. Dry-run returns the plan, no PATCH.',
  "",
  "    posts maps work id -> (thread_ts, permalink) from the adapter.",
  "    trails maps work id -> breadcrumb text for gather.",
  "    A post with no ts does not PATCH. Empty is not recoverable; missing is.",
  '    """',
  "    lines: list[str] = []",
  "    for w, action in plan:",
  "        if not w.page_id:",
  '            lines.append(f"notion  {w.id:16}  skip  no page id")',
  "            continue",
  "        if action == \"post\":",
  "            ts, permalink = posts.get(w.id, (\"\", \"\"))",
  "            if not ts:",
  '                lines.append(f"notion  {w.id:16}  POST    no ts — leave empty, retry next run")',
  "                continue",
  '            lines.append(f"notion  {w.id:16}  POST    write Broadcast TS + Permalink")',
  "            if not dry_run:",
  "                client.write_anchor(w.page_id, ts, permalink)",
  "        elif action == \"gather\":",
  '            lines.append(f"notion  {w.id:16}  GATHER  write Last Status Update")',
  "            if not dry_run:",
  "                client.write_trail(w.page_id, trails.get(w.id, \"silent\"))",
  "        elif action == \"gap\":",
  '            lines.append(f"notion  {w.id:16}  GAP     no write")',
  "        else:",
  '            lines.append(f"notion  {w.id:16}  SKIP    closed")',
  "    return lines",
  "",
  "",
  "def client_from_env(transport: Transport | None = None) -> NotionClient:",
  '    return NotionClient(os.environ.get("NOTION_TOKEN", ""), transport)',
].join("\n");

const TEST_NOTION = [
  "import json",
  "",
  "from mapping import load_mapping",
  "from notion import NotionClient, NotionError, apply_writes, clip, load_work_from_notion, work_from_page",
  "",
  "SAMPLE = \"\"\"---",
  "workspace: growth-chef",
  "platform: slack",
  "scope: team.growth",
  "agent: relay-prime",
  "---",
  "| id | name | role | direction |",
  "|----|------|------|-----------|",
  "| C0MGMT01 | #mgmt | management | in |",
  "| C0REPT02 | #reports | reports | out |",
  "| C0OPS03 | #ops | room | both |",
  '"""',
  "",
  "PAGE = {",
  '    "id": "page-north",',
  '    "properties": {',
  '        "Name": {"type": "title", "title": [{"plain_text": "North Star launch"}]},',
  '        "Scope key": {"type": "rich_text", "rich_text": [{"plain_text": "north-star"}]},',
  '        "Admin Channel": {"type": "rich_text", "rich_text": [{"plain_text": "C0OPS03"}]},',
  '        "Status": {"type": "status", "status": {"name": "In Progress"}},',
  '        "Broadcast TS": {"type": "rich_text", "rich_text": []},',
  '        "Owner": {"type": "rich_text", "rich_text": [{"plain_text": "U08AAAA"}]},',
  "    },",
  "}",
  "",
  "",
  "def test_work_from_page():",
  "    w = work_from_page(PAGE)",
  "    assert w is not None",
  '    assert w.id == "north-star"',
  '    assert w.room == "C0OPS03"',
  '    assert w.state == "active"',
  '    assert w.anchor == ""',
  '    assert w.page_id == "page-north"',
  "",
  "",
  "def test_query_overlays_mapping():",
  "    calls = []",
  "",
  "    def transport(method, url, headers, body):",
  "        calls.append((method, url))",
  '        return {"results": [PAGE], "has_more": False}',
  "",
  '    client = NotionClient("secret_test", transport)',
  "    mapping = load_work_from_notion(load_mapping(SAMPLE), \"db1\", client)",
  "    assert len(mapping.work) == 1",
  '    assert mapping.plan()[0][1] == "post"',
  '    assert calls[0][0] == "POST"',
  '    assert "/databases/db1/query" in calls[0][1]',
  "",
  "",
  "def test_dry_run_does_not_patch():",
  "    calls = []",
  "",
  "    def transport(method, url, headers, body):",
  "        calls.append(method)",
  '        return {"results": [PAGE], "has_more": False}',
  "",
  '    client = NotionClient("secret_test", transport)',
  "    mapping = load_work_from_notion(load_mapping(SAMPLE), \"db1\", client)",
  "    calls.clear()",
  "    lines = apply_writes(client, mapping.plan(), {}, {}, dry_run=True)",
  "    assert any(\"POST\" in line for line in lines)",
  "    assert calls == []",
  "",
  "",
  "def test_live_write_patches_anchor():",
  "    calls = []",
  "",
  "    def transport(method, url, headers, body):",
  "        calls.append((method, url, json.loads(body.decode()) if body else None))",
  '        return {}',
  "",
  '    client = NotionClient("secret_test", transport)',
  "    w = work_from_page(PAGE)",
  "    apply_writes(",
  "        client,",
  '        ((w, "post"),),',
  '        {"north-star": ("1000000000.000002", "https://example.slack.com/archives/C0OPS03/p1000000000002")},',
  "        {},",
  "        dry_run=False,",
  "    )",
  '    assert calls[0][0] == "PATCH"',
  '    assert "/pages/page-north" in calls[0][1]',
  '    ts = calls[0][2]["properties"]["Broadcast TS"]["rich_text"][0]["text"]["content"]',
  '    assert ts == "1000000000.000002"',
  '    link = calls[0][2]["properties"]["Broadcast Permalink"]["rich_text"][0]["text"]["content"]',
  '    assert link.startswith("https://example.slack.com/")',
  "",
  "",
  "def test_post_without_ts_does_not_patch():",
  "    calls = []",
  "",
  "    def transport(method, url, headers, body):",
  "        calls.append(method)",
  '        return {}',
  "",
  '    client = NotionClient("secret_test", transport)',
  "    w = work_from_page(PAGE)",
  '    lines = apply_writes(client, ((w, "post"),), {}, {}, dry_run=False)',
  "    assert calls == []",
  '    assert any("no ts" in line for line in lines)',
  "",
  "",
  "def test_empty_ts_is_refused():",
  "    client = NotionClient(\"secret_test\", lambda *a: {})",
  "    w = work_from_page(PAGE)",
  "    try:",
  '        client.write_anchor(w.page_id, "", "https://example.slack.com/p1")',
  "        raise AssertionError(\"wrote empty Broadcast TS\")",
  "    except NotionError:",
  "        pass",
  "",
  "",
  "def test_clip_marks_truncation():",
  "    out = clip(\"x\" * 3000)",
  "    assert len(out) == 2000",
  '    assert out.endswith("(truncated)")',
  "",
  "",
  'if __name__ == "__main__":',
  "    test_work_from_page()",
  "    test_query_overlays_mapping()",
  "    test_dry_run_does_not_patch()",
  "    test_live_write_patches_anchor()",
  "    test_post_without_ts_does_not_patch()",
  "    test_empty_ts_is_refused()",
  "    test_clip_marks_truncation()",
  '    print("ok")',
].join("\n");

const REQUIREMENTS = [
  "# stdlib is enough for dry-run, URL maps, and mapping tests.",
  "# Live adapters (optional):",
  "# slack-sdk>=3.33",
  "# discord.py>=2.4",
  "",
].join("\n");

export const PYTHON_FILES: RepoFile[] = [
  { path: "agent/python/__init__.py", language: "python", content: INIT },
  { path: "agent/python/relay.py", language: "python", content: RELAY + "\n" },
  { path: "agent/python/mapping.py", language: "python", content: MAPPING + "\n" },
  { path: "agent/python/scope.py", language: "python", content: SCOPE + "\n" },
  { path: "agent/python/report.py", language: "python", content: REPORT + "\n" },
  { path: "agent/python/slack_adapter.py", language: "python", content: SLACK + "\n" },
  { path: "agent/python/discord_adapter.py", language: "python", content: DISCORD + "\n" },
  { path: "agent/python/test_scope.py", language: "python", content: TEST_SCOPE + "\n" },
  { path: "agent/python/test_mapping.py", language: "python", content: TEST_MAPPING + "\n" },
  { path: "agent/python/test_report.py", language: "python", content: TEST_REPORT + "\n" },
  { path: "agent/python/notion.py", language: "python", content: NOTION + "\n" },
  { path: "agent/python/test_notion.py", language: "python", content: TEST_NOTION + "\n" },
  { path: "agent/python/requirements.txt", language: "text", content: REQUIREMENTS },
];
