import type { RepoFile } from "./types";

const RELAY = [
  "#!/usr/bin/env npx tsx",
  "/** Axiom scoped relay — TypeScript runtime. Same contract as the Python agent. */",
  "",
  "import { parseArgs } from \"node:util\";",
  "import { loadMappingFrom } from \"./mapping.ts\";",
  "import { formatReport } from \"./report.ts\";",
  "import { ScopeGuard } from \"./scope.ts\";",
  "import { SlackAdapter } from \"./slack.ts\";",
  "import { DiscordAdapter } from \"./discord.ts\";",
  "",
  "const adapters = { slack: SlackAdapter, discord: DiscordAdapter } as const;",
  "",
  "class Runtime {",
  "  mapping!: Awaited<ReturnType<typeof loadMappingFrom>>;",
  "  guard!: ScopeGuard;",
  "  adapter!: SlackAdapter | DiscordAdapter;",
  "  platform!: keyof typeof adapters;",
  "",
  "  constructor(",
  "    private source: string,",
  "    private platformOverride?: string,",
  "  ) {}",
  "",
  "  async reload(): Promise<void> {",
  "    const mapping = await loadMappingFrom(this.source);",
  "    const platform = (this.platformOverride ?? mapping.platform) as keyof typeof adapters;",
  "    const Adapter = adapters[platform];",
  "    if (!Adapter) {",
  "      console.error(`unknown platform: ${platform}`);",
  "      process.exit(2);",
  "    }",
  "    this.mapping = mapping;",
  "    this.platform = platform;",
  "    this.guard = new ScopeGuard(mapping);",
  "    this.adapter = new Adapter(mapping, this.guard);",
  "  }",
  "}",
  "",
  "const { values } = parseArgs({",
  "  options: {",
  "    mapping: { type: \"string\" },",
  "    platform: { type: \"string\" },",
  '    "dry-run": { type: "boolean", default: false },',
  '    "collect-seconds": { type: "string" },',
  "  },",
  "});",
  "",
  "if (!values.mapping) {",
  '  console.error("usage: axiom-relay --mapping <file|url> [--platform slack|discord] [--dry-run]");',
  "  process.exit(2);",
  "}",
  "",
  "const runtime = new Runtime(values.mapping, values.platform);",
  "await runtime.reload();",
  "",
  "const collect = Number(values[\"collect-seconds\"] ?? runtime.mapping.collectSeconds);",
  "",
  "if (values[\"dry-run\"]) {",
  "  runtime.adapter.describe();",
  "  process.stdout.write(",
  "    formatReport({",
  "      mapping: runtime.mapping,",
  "      guard: runtime.guard,",
  "      broadcastId: runtime.mapping.channels.find((c) => c.role === \"management\")!.id,",
  "      replyCount: 0,",
  "      collectSeconds: collect,",
  "    }),",
  "  );",
  "  process.exit(0);",
  "}",
  "",
  "if (process.platform !== \"win32\") {",
  "  process.on(\"SIGHUP\", () => {",
  "    void runtime.reload();",
  "  });",
  "}",
  "",
  "runtime.adapter.run(collect);",
].join("\n");

const MAPPING = [
  "import { readFileSync } from \"node:fs\";",
  "",
  "export type Role = \"management\" | \"room\" | \"reports\";",
  "export type Direction = \"in\" | \"out\" | \"both\";",
  "export type Platform = \"slack\" | \"discord\";",
  "",
  "export type Channel = {",
  "  id: string;",
  "  name: string;",
  "  role: Role;",
  "  direction: Direction;",
  "};",
  "",
  "export type Mapping = {",
  "  workspace: string;",
  "  platform: Platform;",
  "  scope: string;",
  "  agent: string;",
  "  collectSeconds: number;",
  "  channels: Channel[];",
  "};",
  "",
  "export class MappingError extends Error {}",
  "",
  "export async function readSource(source: string): Promise<string> {",
  '  if (source.startsWith("http://") || source.startsWith("https://")) {',
  '    const res = await fetch(source, { headers: { "User-Agent": "axiom-relay/0.2" } });',
  "    if (!res.ok) throw new MappingError(`mapping fetch ${res.status}`);",
  "    return await res.text();",
  "  }",
  "  return readFileSync(source, \"utf8\");",
  "}",
  "",
  "export async function loadMappingFrom(source: string): Promise<Mapping> {",
  "  return loadMapping(await readSource(source));",
  "}",
  "",
  "export function loadMapping(text: string): Mapping {",
  "  const { meta, body } = splitFrontMatter(text);",
  "  const channels = parseTable(body);",
  "  validate(meta, channels);",
  "  return {",
  "    workspace: meta.workspace,",
  "    platform: meta.platform as Platform,",
  "    scope: meta.scope,",
  "    agent: meta.agent,",
  "    collectSeconds: Number(meta.collect_seconds ?? 45),",
  "    channels,",
  "  };",
  "}",
  "",
  "function splitFrontMatter(text: string): { meta: Record<string, string>; body: string } {",
  '  if (!text.startsWith("---")) throw new MappingError("mapping must start with YAML front matter");',
  "  const end = text.indexOf(\"\\n---\", 3);",
  "  if (end < 0) throw new MappingError(\"unterminated front matter\");",
  "  const raw = text.slice(3, end);",
  "  const body = text.slice(end + 4);",
  "  const meta: Record<string, string> = {};",
  "  for (const line of raw.split(\"\\n\")) {",
  "    if (!line.trim() || !line.includes(\":\")) continue;",
  "    const i = line.indexOf(\":\");",
  "    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();",
  "  }",
  "  return { meta, body };",
  "}",
  "",
  "function parseTable(body: string): Channel[] {",
  "  let header: string[] | null = null;",
  "  const rows: Channel[] = [];",
  "  for (const raw of body.split(\"\\n\")) {",
  "    const line = raw.trim();",
  '    if (!line.startsWith("|")) continue;',
  '    const cells = line.replace(/^\\||\\|$/g, "").split("|").map((c) => c.trim());',
  "    if (!header) {",
  "      header = cells.map((c) => c.toLowerCase());",
  "      continue;",
  "    }",
  '    if (/^[-:\\s|]+$/.test(line)) continue;',
  "    const data: Record<string, string> = {};",
  "    header.forEach((key, i) => {",
  "      data[key] = cells[i] ?? \"\";",
  "    });",
  "    rows.push({",
  "      id: data.id,",
  "      name: data.name ?? \"\",",
  "      role: data.role as Role,",
  "      direction: data.direction as Direction,",
  "    });",
  "  }",
  "  return rows;",
  "}",
  "",
  "function validate(meta: Record<string, string>, channels: Channel[]) {",
  '  for (const key of ["workspace", "platform", "scope", "agent"]) {',
  "    if (!meta[key]) throw new MappingError(`missing ${key}`);",
  "  }",
  '  if (meta.platform !== "slack" && meta.platform !== "discord") {',
  "    throw new MappingError(`unknown platform ${meta.platform}`);",
  "  }",
  "  const ids = channels.map((c) => c.id);",
  "  if (new Set(ids).size !== ids.length) throw new MappingError(\"duplicate channel id\");",
  "  const hasMgmt = channels.some((c) => c.role === \"management\" && c.direction !== \"out\");",
  "  const hasReport = channels.some((c) => c.role === \"reports\" && c.direction !== \"in\");",
  "  if (!hasMgmt) throw new MappingError(\"need a management channel with direction in/both\");",
  "  if (!hasReport) throw new MappingError(\"need a reports channel with direction out/both\");",
  "}",
].join("\n");

const SCOPE = [
  "import type { Mapping } from \"./mapping.ts\";",
  "",
  "export class ScopeError extends Error {}",
  "",
  "export class ScopeGuard {",
  "  readonly scope: string;",
  "  private ids: Set<string>;",
  "",
  "  constructor(mapping: Mapping) {",
  "    this.scope = mapping.scope;",
  "    this.ids = new Set(mapping.channels.map((c) => c.id));",
  "  }",
  "",
  "  allow(channelId: string): boolean {",
  "    return this.ids.has(channelId);",
  "  }",
  "",
  "  redact(channelId: string): string {",
  '    return this.allow(channelId) ? channelId : "<outside-scope>";',
  "  }",
  "",
  "  require(channelId: string, action: string): void {",
  "    if (!this.allow(channelId)) {",
  "      throw new ScopeError(`blocked ${action}: outside scope ${this.scope}`);",
  "    }",
  "  }",
  "",
  "  drop(_channelId: string, reason: string): void {",
  "    console.info(`dropped event source=<outside-scope> reason=${reason}`);",
  "  }",
  "}",
].join("\n");

const REPORT = [
  "import type { Mapping } from \"./mapping.ts\";",
  "import type { ScopeGuard } from \"./scope.ts\";",
  "",
  "export function formatReport(opts: {",
  "  mapping: Mapping;",
  "  guard: ScopeGuard;",
  "  broadcastId: string;",
  "  replyCount: number;",
  "  collectSeconds: number;",
  "}): string {",
  "  opts.guard.require(opts.broadcastId, \"report\");",
  "  const rooms = opts.mapping.channels.filter((c) => c.role === \"room\");",
  "  const reports = opts.mapping.channels.filter((c) => c.role === \"reports\");",
  "  return [",
  "    `# report from ${opts.mapping.agent}`,",
  "    `scope: ${opts.mapping.scope}`,",
  "    `broadcast: ${opts.guard.redact(opts.broadcastId)}`,",
  "    `rooms: ${rooms.length}`,",
  "    `replies: ${opts.replyCount}`,",
  "    `window: ${opts.collectSeconds}s`,",
  "    `filed: ${reports.length} reports channel(s)`,",
  "    \"\",",
  "  ].join(\"\\n\");",
  "}",
].join("\n");

const SLACK = [
  "import type { Mapping } from \"./mapping.ts\";",
  "import type { ScopeGuard } from \"./scope.ts\";",
  "",
  "export class SlackAdapter {",
  "  constructor(",
  "    private mapping: Mapping,",
  "    private guard: ScopeGuard,",
  "  ) {}",
  "",
  "  describe(): void {",
  "    const m = this.mapping;",
  "    console.log(`axiom ${m.agent}  scope=${m.scope}  platform=slack`);",
  "    for (const ch of m.channels) {",
  "      console.log(`  ${ch.role.padEnd(12)} ${ch.direction.padEnd(4)}  ${ch.id}  ${ch.name}`);",
  "    }",
  "    console.log(`fan-out: ${m.channels.filter((c) => c.role === \"room\").length} room(s)`);",
  "  }",
  "",
  "  run(_collectSeconds: number): never {",
  "    for (const ch of this.mapping.channels) this.guard.require(ch.id, \"listen\");",
  '    throw new Error("live Slack requires SLACK_BOT_TOKEN");',
  "  }",
  "}",
].join("\n");

const DISCORD = [
  "import type { Mapping } from \"./mapping.ts\";",
  "import type { ScopeGuard } from \"./scope.ts\";",
  "",
  "export class DiscordAdapter {",
  "  constructor(",
  "    private mapping: Mapping,",
  "    private guard: ScopeGuard,",
  "  ) {}",
  "",
  "  describe(): void {",
  "    const m = this.mapping;",
  "    console.log(`axiom ${m.agent}  scope=${m.scope}  platform=discord`);",
  "    for (const ch of m.channels) {",
  "      console.log(`  ${ch.role.padEnd(12)} ${ch.direction.padEnd(4)}  ${ch.id}  ${ch.name}`);",
  "    }",
  "  }",
  "",
  "  run(_collectSeconds: number): never {",
  "    for (const ch of this.mapping.channels) this.guard.require(ch.id, \"listen\");",
  '    throw new Error("live Discord requires DISCORD_BOT_TOKEN");',
  "  }",
  "}",
].join("\n");

const PKG = `{
  "name": "@axiom/scoped-relay",
  "version": "0.2.0",
  "type": "module",
  "license": "MIT",
  "bin": {
    "axiom-relay": "./relay.ts"
  },
  "scripts": {
    "dry-run": "npx tsx relay.ts --mapping ../../examples/mapping.md --dry-run"
  }
}
`;

const TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "types": ["node"]
  }
}
`;

export const NODE_FILES: RepoFile[] = [
  { path: "agent/node/relay.ts", language: "typescript", content: RELAY + "\n" },
  { path: "agent/node/mapping.ts", language: "typescript", content: MAPPING + "\n" },
  { path: "agent/node/scope.ts", language: "typescript", content: SCOPE + "\n" },
  { path: "agent/node/report.ts", language: "typescript", content: REPORT + "\n" },
  { path: "agent/node/slack.ts", language: "typescript", content: SLACK + "\n" },
  { path: "agent/node/discord.ts", language: "typescript", content: DISCORD + "\n" },
  { path: "agent/node/package.json", language: "json", content: PKG },
  { path: "agent/node/tsconfig.json", language: "json", content: TSCONFIG },
];
