/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AxiomsRouteImport } from './routes/axioms'
import { Route as CommitsRouteImport } from './routes/commits'
import { Route as BlobSplatRouteImport } from './routes/blob.$'
import { Route as CommitHashRouteImport } from './routes/commit.$hash'
import { Route as TreeSplatRouteImport } from './routes/tree.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AxiomsRoute = AxiomsRouteImport.update({
  id: '/axioms',
  path: '/axioms',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitsRoute = CommitsRouteImport.update({
  id: '/commits',
  path: '/commits',
  getParentRoute: () => rootRouteImport,
} as any)
const BlobSplatRoute = BlobSplatRouteImport.update({
  id: '/blob/$',
  path: '/blob/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitHashRoute = CommitHashRouteImport.update({
  id: '/commit/$hash',
  path: '/commit/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeSplatRoute = TreeSplatRouteImport.update({
  id: '/tree/$',
  path: '/tree/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/axioms': typeof AxiomsRoute
  '/commits': typeof CommitsRoute
  '/blob/$': typeof BlobSplatRoute
  '/commit/$hash': typeof CommitHashRoute
  '/tree/$': typeof TreeSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/axioms': typeof AxiomsRoute
  '/commits': typeof CommitsRoute
  '/blob/$': typeof BlobSplatRoute
  '/commit/$hash': typeof CommitHashRoute
  '/tree/$': typeof TreeSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ask': typeof AskRoute
  '/axioms': typeof AxiomsRoute
  '/commits': typeof CommitsRoute
  '/blob/$': typeof BlobSplatRoute
  '/commit/$hash': typeof CommitHashRoute
  '/tree/$': typeof TreeSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ask'
    | '/axioms'
    | '/commits'
    | '/blob/$'
    | '/commit/$hash'
    | '/tree/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ask'
    | '/axioms'
    | '/commits'
    | '/blob/$'
    | '/commit/$hash'
    | '/tree/$'
  id:
    | '__root__'
    | '/'
    | '/ask'
    | '/axioms'
    | '/commits'
    | '/blob/$'
    | '/commit/$hash'
    | '/tree/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AskRoute: typeof AskRoute
  AxiomsRoute: typeof AxiomsRoute
  CommitsRoute: typeof CommitsRoute
  BlobSplatRoute: typeof BlobSplatRoute
  CommitHashRoute: typeof CommitHashRoute
  TreeSplatRoute: typeof TreeSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axioms': {
      id: '/axioms'
      path: '/axioms'
      fullPath: '/axioms'
      preLoaderRoute: typeof AxiomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commits': {
      id: '/commits'
      path: '/commits'
      fullPath: '/commits'
      preLoaderRoute: typeof CommitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blob/$': {
      id: '/blob/$'
      path: '/blob/$'
      fullPath: '/blob/$'
      preLoaderRoute: typeof BlobSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commit/$hash': {
      id: '/commit/$hash'
      path: '/commit/$hash'
      fullPath: '/commit/$hash'
      preLoaderRoute: typeof CommitHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree/$': {
      id: '/tree/$'
      path: '/tree/$'
      fullPath: '/tree/$'
      preLoaderRoute: typeof TreeSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AskRoute: AskRoute,
  AxiomsRoute: AxiomsRoute,
  CommitsRoute: CommitsRoute,
  BlobSplatRoute: BlobSplatRoute,
  CommitHashRoute: CommitHashRoute,
  TreeSplatRoute: TreeSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
